import { useState } from 'react';

import { SwitchAccountSelectors } from '@tests/selectors/switch-account.selectors';
import { Stack } from 'leather-styles/jsx';

import { makeAccountIdentifer } from '@leather.io/crypto';
import type { AccountId } from '@leather.io/models';
import { Button, Input, Sheet, SheetHeader } from '@leather.io/ui';

import { getAutogeneratedAccountDisplayName } from '@app/common/utils/get-account-display-name';
import { ButtonRow } from '@app/components/layout/card/components/button-row';
import { useAppDispatch } from '@app/store';
import { clearAccountName, renameAccount } from '@app/store/accounts/accounts.actions';
import { useAccountNameOverride } from '@app/store/accounts/accounts.selectors';

const ACCOUNT_MAX_NAME_LENGTH = 35;

interface RenameAccountDialogProps {
  accountId: AccountId;
  isShowing: boolean;
  onClose(): void;
}

export function RenameAccountDialog({ accountId, isShowing, onClose }: RenameAccountDialogProps) {
  const dispatch = useAppDispatch();
  const customName = useAccountNameOverride(accountId);
  const [name, setName] = useState(
    customName ?? getAutogeneratedAccountDisplayName(accountId.accountIndex)
  );

  function handleSave() {
    const accountIdentifier = makeAccountIdentifer(accountId.fingerprint, accountId.accountIndex);
    const trimmed = name.trim().substring(0, ACCOUNT_MAX_NAME_LENGTH);
    if (trimmed) {
      void dispatch(renameAccount(accountIdentifier, trimmed));
    } else {
      void dispatch(clearAccountName(accountIdentifier));
    }
    onClose();
  }

  if (!isShowing) return null;

  return (
    <Sheet
      header={<SheetHeader title="Rename account" />}
      isShowing={isShowing}
      onClose={onClose}
      footer={
        <ButtonRow flexDirection="row">
          <Button variant="outline" flexGrow={1} onClick={onClose}>
            Cancel
          </Button>
          <Button
            data-testid={SwitchAccountSelectors.RenameAccountSaveBtn}
            flexGrow={1}
            onClick={handleSave}
          >
            Save
          </Button>
        </ButtonRow>
      }
    >
      <Stack gap="space.05" px="space.05" pt="space.05" pb="space.05">
        <Input.Root>
          <Input.Label>Account name</Input.Label>
          <Input.Field
            autoFocus
            data-testid={SwitchAccountSelectors.RenameAccountInput}
            value={name}
            maxLength={ACCOUNT_MAX_NAME_LENGTH}
            onChange={e => setName(e.currentTarget.value)}
            onKeyDown={e => {
              if (e.key === 'Enter') handleSave();
            }}
          />
        </Input.Root>
      </Stack>
    </Sheet>
  );
}
