import { useState } from 'react';

import { SwitchAccountSelectors } from '@tests/selectors/switch-account.selectors';
import { Flex, Stack } from 'leather-styles/jsx';

import { makeAccountIdentifer } from '@leather.io/crypto';
import type { AccountId } from '@leather.io/models';
import { Button, Input, Sheet, SheetHeader } from '@leather.io/ui';

import { getAutogeneratedAccountDisplayName } from '@app/common/utils/get-account-display-name';
import { useAppDispatch } from '@app/store';
import { useAccountNameOverride } from '@app/store/accounts/accounts.selectors';
import { userRenamesAccount } from '@app/store/accounts/accounts.slice';

const ACCOUNT_MAX_NAME_LENGTH = 35;

interface RenameAccountDialogProps {
  accountId: AccountId;
  isShowing: boolean;
  onClose(): void;
}

export function RenameAccountDialog({ accountId, isShowing, onClose }: RenameAccountDialogProps) {
  const dispatch = useAppDispatch();
  const customName = useAccountNameOverride(accountId);
  const [name, setName] = useState(
    customName ?? getAutogeneratedAccountDisplayName(accountId.accountIndex)
  );

  function handleSave() {
    const trimmed = name.trim().substring(0, ACCOUNT_MAX_NAME_LENGTH);
    if (!trimmed) return;
    dispatch(
      userRenamesAccount({
        accountId: makeAccountIdentifer(accountId.fingerprint, accountId.accountIndex),
        name: trimmed,
      })
    );
    onClose();
  }

  if (!isShowing) return null;

  return (
    <Sheet header={<SheetHeader title="Rename account" />} isShowing={isShowing} onClose={onClose}>
      <Stack gap="space.05" px="space.05" pb="space.05">
        <Input.Root>
          <Input.Label>Account name</Input.Label>
          <Input.Field
            autoFocus
            data-testid={SwitchAccountSelectors.RenameAccountInput}
            value={name}
            maxLength={ACCOUNT_MAX_NAME_LENGTH}
            onChange={e => setName(e.currentTarget.value)}
            onKeyDown={e => {
              if (e.key === 'Enter') handleSave();
            }}
          />
        </Input.Root>
        <Flex gap="space.04" justifyContent="flex-end">
          <Button variant="outline" onClick={onClose}>
            Cancel
          </Button>
          <Button
            data-testid={SwitchAccountSelectors.RenameAccountSaveBtn}
            onClick={handleSave}
            disabled={!name.trim()}
          >
            Save
          </Button>
        </Flex>
      </Stack>
    </Sheet>
  );
}
