default_platform(:android)

platform :android do
  desc "Build and distribute Android app"
  lane :distribute_android do
    gradle(
      task: "assembleRelease"
    )
    firebase_app_distribution(
      app: "1:915379517791:android:d4e7cb446a612f8c789eea",
      group: "leatherhood",
      release_notes: "New build available"
    )
  end

  lane :build do
    gym(
      workspace: "YourApp.xcworkspace",
      scheme: "leatherwalletmobile",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "io.leather.mobilewallet" => "leatherhood"
        }
      },
      xcargs: "-allowProvisioningUpdates"
    )
  end
end