name: Android Maestro Test

on:
  pull_request:
    paths:
      - '../../../apps/mobile/**'
      - '../../../packages/**'
      - '!../../../packages/ui/**/*.web.ts'
      - '!../../../packages/ui/**/*.web.tsx'

jobs:
  initialize:
    steps:
      - uses: eas/checkout

  build_android:
    name: Build Android
    needs: [initialize]
    type: build
    params:
      platform: android
      profile: maestro

  maestro_test_android:
    name: Maestro Test Android
    type: maestro
    needs: [build_android]
    environment: development
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      flow_path:
        - maestro/flows/smoketests.yaml
