name: iOS Maestro Test

on:
  push:
    branches:
      - dev
      - main
  pull_request_labeled:
    labels:
      - needs:e2e-tests
jobs:
  initialize:
    steps:
      - uses: eas/checkout

  build_ios:
    name: Build iOS
    needs: [initialize]
    type: build
    params:
      platform: ios
      profile: maestro

  maestro_test_ios:
    name: Maestro Test iOS
    type: maestro
    needs: [build_ios]
    environment: development
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      flow_path:
        - maestro/flows/accounts-drawer.yaml
        - maestro/flows/accounts-page.yaml
        - maestro/flows/change-network.yaml
        - maestro/flows/change-theme.yaml
        - maestro/flows/create-wallet-without-security.yaml
        # Failing tests:
        # - maestro/flows/change-account-icon.yaml
        # - maestro/flows/hide-account.yaml
        # - maestro/flows/receive.yaml
        # - maestro/flows/restore-wallet.yaml
        # - maestro/flows/send.yaml
        # - maestro/flows/settings-guides.yaml
        # - maestro/flows/settings-learn.yaml
        # - maestro/flows/settings-support.yaml
        # - maestro/flows/wallet-add-account.yaml
        # - maestro/flows/wallet-management.yaml
        # - maestro/flows/wallet-multi-wallet.yaml
