name: iOS Maestro Test

on:
  pull_request:
    paths:
      - '../../../apps/mobile/**'
      - '../../../packages/**'
      - '!../../../packages/ui/**/*.web.ts'
      - '!../../../packages/ui/**/*.web.tsx'

jobs:
  initialize:
    steps:
      - uses: eas/checkout

  build_ios:
    name: Build iOS
    needs: [initialize]
    type: build
    params:
      platform: ios
      profile: maestro

  maestro_test_ios:
    name: Maestro Test iOS
    type: maestro
    needs: [build_ios]
    environment: development
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      flow_path:
        - maestro/flows/smoketests.yaml
