workers_dev = true
name = "leather-web"
compatibility_date = "2024-11-18"
compatibility_flags = [ "nodejs_compat" ]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }
send_metrics = false

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"

[observability]
enabled = true
head_sampling_rate = 1
