export enum AppRoutes {
  Home = '/',
  DeveloperConsole = '/developer-console',
  DeveloperConsoleWalletManager = '/developer-console/wallet-manager',
  DeveloperBitcoinScratchPad = '/developer-console/bitcoin-scratch-pad',
  Balances = '/balances',
  Collectibles = '/collectibles',
  CreateNewWallet = '/create-new-wallet',
  RecoverWallet = '/recover-wallet',
  SecureYourWallet = '/secure-your-wallet',
  GeneratingWallet = '/generating-wallet',
  MpcWallets = '/mpc-wallets',
  HardwareWallets = '/hardware-wallets',

  // Account
  Account = '/account/[accountId]',
  Activity = '/activity',
  AccountActivity = '/account/[accountId]/activity',
  AccountBalances = '/account/[accountId]/balances',
  AccountCollectibles = '/account/[accountId]/collectibles',
  // Settings
  Settings = '/settings',
  SettingsDisplay = '/settings/display',
  SettingsSecurity = '/settings/security',
  SettingsNetworks = '/settings/networks',
  SettingsNotifications = '/settings/notifications',
  SettingsNotificationsEmail = '/settings/notifications/email',
  SettingsHelp = '/settings/help',
  SettingsWallet = '/settings/wallet',
  SettingsWalletHiddenAccounts = '/settings/wallet/hidden-accounts',
  SettingsWalletConfigureWallet = '/settings/wallet/configure/[wallet]',
  SettingsWalletConfigureAccount = '/settings/wallet/configure/[wallet]/[account]',
  SettingsWalletConfigureAccountAvatar = '/settings/wallet/configure/[wallet]/[account]/choose-avatar',
  SettingsWalletConfigureViewSecretKey = '/settings/wallet/configure/[wallet]/view-secret-key',
}
