default_platform(:ios)

desc "Build and distribute iOS app"

lane :build_ios do
  if is_ci  
    setup_ci
  end
  match(type: "appstore", readonly: true)
  build_app(
    scheme: "leatherwalletmobile"
  )
end

lane :increment_version do
  increment_version_number(
    bump_type: "patch" # Options are: "patch", "minor", "major"
  )
  # Optionally, you can also increment the build number
  increment_build_number
end

lane :notify_slack do
  Dotenv.load('./.env')
  slack(
    message: "iOS build completed successfully!",
    channel: "#leather-mobile",
    slack_url: ENV["SLACK_WEBHOOK_URL"]
  )
end

lane :distribute_ios do
  build_ios
  increment_version
  firebase_app_distribution(
    app: "1:915379517791:ios:ecfa47ab5ee5f256789eea",
    groups: "leatherhood",
    release_notes: "New iOS build available",
      )
  notify_slack
end


