name: provision
description: Set up job with tasks needed to run a code check
inputs:
  PROVISION_MOBILE:
    description: 'Boolean value to identify if this is running on the main branch or not'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: '10.26.0+sha512.3b3f6c725ebe712506c0ab1ad4133cf86b1f4b687effce62a9b38b4d72e3954242e643190fc51fa1642949c735f403debd44f5cb0edd657abe63a8b6a7e1e402'

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org/'
        cache: 'pnpm'

    - run: pnpm install --ignore-scripts
      env:
        PROVISION_MOBILE: ${{ inputs.PROVISION_MOBILE }}
      shell: bash

    - name: build-panda
      run: pnpm turbo run build --filter="@leather.io/panda-preset"
      shell: bash
