name: Provision
description: Set up job with tasks needed to run a code check
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: '10.4.1'

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org/'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Build local dependencies
      run: pnpm turbo run build --force --no-cache
      shell: bash
