import { spawnSync } from 'node:child_process';
import { appendFileSync, mkdirSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const manifestPath = resolve(repoRoot, 'package.json');
const lockfilePath = resolve(repoRoot, 'pnpm-lock.yaml');
const reportPath = resolve(repoRoot, 'tmp/audit-fix-report.md');

const auditArgs = [
  'dlx',
  'pnpm@11.0.0-rc.1',
  'audit',
  '--prod',
  '--audit-level',
  'high',
  '--json',
  '--config.manage-package-manager-versions=false',
];
const installArgs = ['install', '--lockfile-only', '--ignore-scripts', '--no-frozen-lockfile'];
const maxOutputBytes = 256 * 1024 * 1024;

const defaultTitle = 'fix: dependency audit';
const maxTitleLength = 72;
const maxErrorLength = 300;

const packageNamePattern = /^(?:@[a-z0-9][a-z0-9._-]*\/)?[a-z0-9][a-z0-9._-]*$/;
const versionPattern = /^(\d+)\.(\d+)\.(\d+)$/;
const firstPatchedPattern = /^>=\s*(\d+\.\d+\.\d+)$/;
const noPatchPattern = /^(?:<\s*0\.0\.0)?$/;
const immatureReleasePattern = /ERR_PNPM_NO_MATURE_MATCHING_VERSION/;
const unpublishedReleasePattern = /ERR_PNPM_NO_MATCHING_VERSION/;
const pnpmErrorPattern = /ERR_PNPM_\S+[^\n]*/;

const reportHeader =
  'Automated fix for the `audit-dependencies` gate, generated by `repo:audit-fix`.';
const nothingFixedNote =
  'Nothing could be fixed automatically, so this pull request has no changes yet. Push the manual ' +
  'fix to this branch: the bot leaves the branch alone once it carries a commit that is not its own.';
const todoIntro =
  'These advisories still fail the gate. Each item says what is blocking it and what to do.';

export function parseVersion(text) {
  const match = versionPattern.exec(text.trim());
  if (!match) return null;
  return [Number(match[1]), Number(match[2]), Number(match[3])];
}

export function compareVersions(a, b) {
  const index = a.findIndex((part, position) => part !== b[position]);
  if (index === -1) return 0;
  return a[index] - b[index];
}

function manual(todo) {
  return { status: 'manual', todo };
}

function describeIgnore(advisory) {
  return (
    `if the package never runs in a shipped app, add \`${advisory.github_advisory_id}\` to ` +
    '`auditConfig.ignoreGhsas` in `pnpm-workspace.yaml` with a comment saying why it is not ' +
    'exploitable and when to remove the entry'
  );
}

export function planOverride(advisory) {
  const name = advisory.module_name ?? '';
  if (!packageNamePattern.test(name)) {
    return manual('The advisory names a package this script does not recognise. Check it by hand.');
  }

  const patchedRange = (advisory.patched_versions ?? '').trim();
  if (noPatchPattern.test(patchedRange)) {
    return manual(
      `No fixed release exists. Replace or remove the dependency, or ${describeIgnore(advisory)}.`
    );
  }

  const patchedMatch = firstPatchedPattern.exec(patchedRange);
  if (!patchedMatch) {
    return manual(
      `The patched range \`${patchedRange}\` is not a single version. Pick the fixed release in ` +
        'the installed major and add an entry for it to `pnpm.overrides` in `package.json`.'
    );
  }

  const patched = parseVersion(patchedMatch[1]);
  const [major, minor] = patched;
  const floor = major > 0 ? [major, 0, 0] : [0, minor, 0];
  const ceiling = major > 0 ? [major + 1, 0, 0] : [0, minor + 1, 0];
  const cap = major > 0 ? String(major + 1) : ceiling.join('.');
  const range = `>=${patched.join('.')} <${cap}`;

  const outside = (advisory.findings ?? [])
    .map(finding => finding.version)
    .filter(version => {
      const installed = parseVersion(version);
      return (
        installed === null ||
        compareVersions(installed, floor) < 0 ||
        compareVersions(installed, ceiling) >= 0
      );
    });
  if (outside.length > 0) {
    return manual(
      `Installed ${[...new Set(outside)].join(', ')} is outside the patched release line ` +
        `\`${range}\`, so the fix crosses a breaking version. Bump the dependency that pulls it in, ` +
        `or add \`"${name}@<${patched.join('.')}": "${range}"\` to \`pnpm.overrides\` after checking ` +
        'that its dependents work with the newer line.'
    );
  }

  return {
    status: 'fixable',
    selector: `${name}@>=${floor.join('.')} <${patched.join('.')}`,
    range,
    patched,
  };
}

export function compareFixes(a, b) {
  const byName = a.advisory.module_name.localeCompare(b.advisory.module_name);
  if (byName !== 0) return byName;
  return compareVersions(a.plan.patched, b.plan.patched);
}

export function mergeOverrides(manifest, fixes) {
  const added = Object.fromEntries(fixes.map(({ plan }) => [plan.selector, plan.range]));
  const overrides = { ...manifest.pnpm?.overrides, ...added };
  return { ...manifest, pnpm: { ...manifest.pnpm, overrides } };
}

function describeEntry(plan) {
  return `\`"${plan.selector}": "${plan.range}"\``;
}

export function describeInstallFailure(output, { advisory, plan }) {
  if (immatureReleasePattern.test(output)) {
    return (
      'The fixed release is newer than `minimumReleaseAge` allows, so later runs retry it ' +
      `automatically. To ship it now, add \`${advisory.module_name}\` to ` +
      '`minimumReleaseAgeExclude` in `pnpm-workspace.yaml` and ' +
      `${describeEntry(plan)} to \`pnpm.overrides\` in \`package.json\`.`
    );
  }
  if (unpublishedReleasePattern.test(output)) {
    return (
      `The fixed release is not on npm: no published version satisfies \`${plan.range}\`. ` +
      `Wait for it, or ${describeIgnore(advisory)}.`
    );
  }
  const lines = output.split('\n').filter(line => line.trim() !== '');
  const error = pnpmErrorPattern.exec(output)?.[0] ?? lines.at(-1) ?? 'no output';
  return (
    `\`pnpm install\` rejected ${describeEntry(plan)}: ` +
    `${error.trim().slice(0, maxErrorLength)}. Resolve it by hand.`
  );
}

export function describeStillReported({ advisory, plan }) {
  return (
    `${describeEntry(plan)} was added but the advisory is still reported, so another override ` +
    `or a pinned parent takes precedence. Check \`pnpm why ${advisory.module_name}\`.`
  );
}

function describeAdvisory(advisory) {
  const name = packageNamePattern.test(advisory.module_name ?? '')
    ? advisory.module_name
    : 'unrecognised package';
  return `\`${name}\` [${advisory.github_advisory_id}](${advisory.url}) (${advisory.severity})`;
}

function describeContext(advisory) {
  const findings = advisory.findings ?? [];
  const versions = [...new Set(findings.map(finding => finding.version))];
  const paths = findings.flatMap(finding => finding.paths ?? []);
  const installed = versions.length > 0 ? `, installed ${versions.join(', ')}` : '';
  if (paths.length === 0) return installed;
  const more = paths.length > 1 ? ` (+${paths.length - 1} more)` : '';
  return `${installed}, reached through \`${paths[0]}\`${more}`;
}

function buildSection(heading, lines) {
  if (lines.length === 0) return [];
  return ['', heading, '', ...lines];
}

export function buildReport(fixes, todos) {
  const added = fixes.map(
    ({ advisory, plan }) => `- ${describeAdvisory(advisory)}: ${describeEntry(plan)}`
  );
  const open = todos.flatMap(({ advisory, todo }) => [
    `- [ ] ${describeAdvisory(advisory)}${describeContext(advisory)}`,
    `  ${todo}`,
  ]);
  const lines = [
    reportHeader,
    ...(fixes.length === 0 && todos.length > 0 ? ['', nothingFixedNote] : []),
    ...buildSection('## Overrides added', added),
    ...buildSection('## Needs a human', open.length > 0 ? [todoIntro, '', ...open] : []),
  ];
  return `${lines.join('\n')}\n`;
}

export function buildTitle(names) {
  if (names.length === 0) return defaultTitle;
  const list =
    names.length === 1 ? names[0] : `${names.slice(0, -1).join(', ')} and ${names.at(-1)}`;
  const title = `fix: ${list} audit`;
  if (title.length > maxTitleLength) return defaultTitle;
  return title;
}

function runPnpm(args) {
  const result = spawnSync('pnpm', args, {
    cwd: repoRoot,
    encoding: 'utf8',
    maxBuffer: maxOutputBytes,
  });
  if (result.error) throw result.error;
  return {
    status: result.status,
    stdout: result.stdout,
    output: `${result.stdout}\n${result.stderr}`,
  };
}

function runAudit() {
  const result = runPnpm(auditArgs);
  const advisories = JSON.parse(result.stdout).advisories;
  if (typeof advisories !== 'object' || advisories === null) {
    throw new Error(`pnpm audit returned no advisory report:\n${result.output}`);
  }
  return Object.values(advisories);
}

function applyOverride(fix) {
  const manifest = readFileSync(manifestPath, 'utf8');
  const lockfile = readFileSync(lockfilePath, 'utf8');
  const next = mergeOverrides(JSON.parse(manifest), [fix]);
  writeFileSync(manifestPath, `${JSON.stringify(next, null, 2)}\n`);

  const install = runPnpm(installArgs);
  if (install.status === 0) return null;

  writeFileSync(manifestPath, manifest);
  writeFileSync(lockfilePath, lockfile);
  return install.output;
}

function main() {
  const planned = runAudit().map(advisory => ({ advisory, plan: planOverride(advisory) }));
  const todos = planned
    .filter(({ plan }) => plan.status === 'manual')
    .map(({ advisory, plan }) => ({ advisory, todo: plan.todo }));

  const fixes = [];
  for (const fix of planned.filter(({ plan }) => plan.status === 'fixable').sort(compareFixes)) {
    const failure = applyOverride(fix);
    if (failure === null) fixes.push(fix);
    else todos.push({ advisory: fix.advisory, todo: describeInstallFailure(failure, fix) });
  }

  if (fixes.length > 0) {
    const reported = new Set(runAudit().map(advisory => advisory.id));
    for (const fix of fixes.filter(({ advisory }) => reported.has(advisory.id))) {
      todos.push({ advisory: fix.advisory, todo: describeStillReported(fix) });
    }
  }

  const report = buildReport(fixes, todos);
  mkdirSync(dirname(reportPath), { recursive: true });
  writeFileSync(reportPath, report);
  process.stdout.write(report);

  if (!process.env.GITHUB_OUTPUT) return;
  const names = [...new Set(fixes.map(({ advisory }) => advisory.module_name))].sort();
  appendFileSync(
    process.env.GITHUB_OUTPUT,
    `changed=${fixes.length > 0}\nunresolved=${todos.length}\ntitle=${buildTitle(names)}\n`
  );
}

if (process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
