import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { delimiter, join } from 'node:path';
import { after, describe, it } from 'node:test';
import { fileURLToPath, pathToFileURL } from 'node:url';

import {
  buildReport,
  buildTitle,
  compareFixes,
  compareVersions,
  describeDroppedVersions,
  describeInstallFailure,
  describeStillReported,
  findDroppedVersions,
  mergeOverrides,
  parseVersion,
  planOverride,
} from './audit-fix.mjs';

const scriptPath = fileURLToPath(new URL('./audit-fix.mjs', import.meta.url));
const rootManifestPath = fileURLToPath(new URL('../../package.json', import.meta.url));

const expectedAuditArgs = [
  'dlx',
  'pnpm@11.0.0-rc.1',
  'audit',
  '--prod',
  '--audit-level',
  'high',
  '--json',
  '--config.manage-package-manager-versions=false',
];
const expectedInstallArgs = [
  'install',
  '--lockfile-only',
  '--ignore-scripts',
  '--no-frozen-lockfile',
];
const reportHeader =
  'Automated fix for the `audit-dependencies` gate, generated by `repo:audit-fix`.';
const nothingFixedNote =
  'Nothing could be fixed automatically, so this pull request has no changes. Make the manual fix ' +
  'on a branch of your own: the bot rebuilds this branch and overwrites anything pushed to it.';
const todoIntro =
  'These advisories still fail the gate. Each item says what is blocking it and what to do.';
const defaultTitle = 'fix: dependency audit';
const maxTitleLength = 72;
const maxBufferBytes = 64 * 1024 * 1024;

const immatureError =
  'ERR_PNPM_NO_MATURE_MATCHING_VERSION  Version 1.8.2 (released 1 day ago) of compression does not meet the minimumReleaseAge constraint';
const unpublishedError =
  'ERR_PNPM_NO_MATCHING_VERSION  No matching version found for compression@>=1.8.2 <2 while fetching it from https://registry.npmjs.org/';
const registryError = 'ERR_PNPM_FETCH_503  GET https://registry.npmjs.org/compression: Unavailable';

const sourceMapAdvisory = {
  id: 1241209,
  title: 'source-map-js allows event-loop denial of service',
  module_name: 'source-map-js',
  vulnerable_versions: '>=1.0.0 <1.2.2',
  patched_versions: '>=1.2.2',
  severity: 'high',
  github_advisory_id: 'GHSA-68fv-2mgg-jv7q',
  url: 'https://github.com/advisories/GHSA-68fv-2mgg-jv7q',
  findings: [
    {
      version: '1.2.1',
      paths: [
        'apps__extension>mixpanel-browser>@mixpanel/rrweb>postcss>source-map-js',
        'apps__extension>postcss-preset-env>postcss>source-map-js',
        'apps__web>postcss>source-map-js',
      ],
    },
  ],
};
const proxyAddrAdvisory = {
  id: 1241210,
  title: 'proxy-addr vulnerable to IP spoofing via IPv4-mapped IPv6 trust subnet',
  module_name: 'proxy-addr',
  vulnerable_versions: '>=1.1.0 <2.0.8',
  patched_versions: '>=2.0.8',
  severity: 'critical',
  github_advisory_id: 'GHSA-jqcg-44mw-7w3h',
  url: 'https://github.com/advisories/GHSA-jqcg-44mw-7w3h',
  findings: [{ version: '2.0.7', paths: ['apps__web>@react-router/serve>express>proxy-addr'] }],
};
const compressionAdvisory = {
  id: 1241221,
  title: 'compression vulnerable to Denial of Service via memory leak',
  module_name: 'compression',
  vulnerable_versions: '<1.8.2',
  patched_versions: '>=1.8.2',
  severity: 'high',
  github_advisory_id: 'GHSA-vc2v-76pw-4v95',
  url: 'https://github.com/advisories/GHSA-vc2v-76pw-4v95',
  findings: [{ version: '1.8.1', paths: ['apps__mobile>expo>@expo/cli>compression'] }],
};
const unpatchedAdvisory = {
  id: 1241300,
  title: 'node-forge signature verification bypass',
  module_name: 'node-forge',
  vulnerable_versions: '<=1.4.0',
  patched_versions: '<0.0.0',
  severity: 'high',
  github_advisory_id: 'GHSA-86w9-cpqp-85rv',
  url: 'https://github.com/advisories/GHSA-86w9-cpqp-85rv',
  findings: [{ version: '1.4.0', paths: ['apps__mobile>expo>@expo/cli>node-forge'] }],
};
const crossMajorAdvisory = {
  ...proxyAddrAdvisory,
  id: 1241400,
  findings: [{ version: '1.1.0', paths: ['apps__web>legacy-server>proxy-addr'] }],
};

const unpatchedTodo =
  'No fixed release exists. Replace or remove the dependency, or if the package never runs in a ' +
  'shipped app, add `GHSA-86w9-cpqp-85rv` to `auditConfig.ignoreGhsas` in `pnpm-workspace.yaml` ' +
  'with a comment saying why it is not exploitable and when to remove the entry.';
const crossMajorTodo =
  'Installed 1.1.0 is outside the patched release line `>=2.0.8 <3`, so the fix crosses a ' +
  'breaking version. Bump the dependency that pulls it in, or add ' +
  '`"proxy-addr@<2.0.8": ">=2.0.8 <3"` to `pnpm.overrides` after checking that its dependents ' +
  'work with the newer line.';

function createAdvisory(overrides = {}) {
  return { ...proxyAddrAdvisory, ...overrides };
}

function createAuditReport(advisories) {
  return {
    advisories: Object.fromEntries(advisories.map(advisory => [advisory.id, advisory])),
    metadata: { vulnerabilities: { high: advisories.length } },
  };
}

function pickOverride(advisory) {
  const plan = planOverride(advisory);
  assert.equal(plan.status, 'fixable', plan.todo);
  return { selector: plan.selector, range: plan.range };
}

function pickTodo(advisory) {
  const plan = planOverride(advisory);
  assert.equal(plan.status, 'manual');
  assert.deepEqual(Object.keys(plan), ['status', 'todo']);
  return plan.todo;
}

function createFix(advisory) {
  const plan = planOverride(advisory);
  assert.equal(plan.status, 'fixable', plan.todo);
  return { advisory, plan };
}

describe('parseVersion', () => {
  const valid = [
    ['0.0.0', [0, 0, 0]],
    ['1.2.3', [1, 2, 3]],
    ['7.29.1', [7, 29, 1]],
    ['10.20.30', [10, 20, 30]],
    ['  2.0.8  ', [2, 0, 8]],
    ['2.0.8\n', [2, 0, 8]],
  ];
  for (const [text, expected] of valid) {
    it(`parses ${JSON.stringify(text)}`, () => {
      assert.deepEqual(parseVersion(text), expected);
    });
  }

  const invalid = [
    '',
    ' ',
    '1',
    '1.2',
    '1.2.3.4',
    'v1.2.3',
    '1.2.x',
    '1.2.3-rc.1',
    '1.2.3-0',
    '1.2.3+build.5',
    '>=1.2.3',
    '^1.2.3',
    '1.2.3 || 2.0.0',
    'latest',
    '1..3',
    '-1.2.3',
    '1.2.3 4.5.6',
  ];
  for (const text of invalid) {
    it(`rejects ${JSON.stringify(text)}`, () => {
      assert.equal(parseVersion(text), null);
    });
  }

  it('returns numbers rather than strings', () => {
    assert.ok(parseVersion('01.002.0003').every(part => typeof part === 'number'));
    assert.deepEqual(parseVersion('01.002.0003'), [1, 2, 3]);
  });
});

describe('compareVersions', () => {
  it('returns zero for equal versions', () => {
    assert.equal(compareVersions([1, 2, 3], [1, 2, 3]), 0);
  });

  const ordered = [
    ['1.0.0', '2.0.0'],
    ['1.2.0', '1.3.0'],
    ['1.2.3', '1.2.4'],
    ['1.9.9', '2.0.0'],
    ['1.2.9', '1.3.0'],
    ['7.3.9', '7.29.1'],
    ['9.0.0', '10.0.0'],
    ['0.9.0', '0.10.0'],
  ];
  for (const [lower, higher] of ordered) {
    it(`orders ${lower} before ${higher}`, () => {
      assert.ok(compareVersions(parseVersion(lower), parseVersion(higher)) < 0);
      assert.ok(compareVersions(parseVersion(higher), parseVersion(lower)) > 0);
    });
  }

  it('sorts a list numerically when used as a comparator', () => {
    const versions = ['7.29.1', '7.3.9', '10.0.0', '0.10.0', '0.9.0', '7.3.10'].map(parseVersion);
    const sorted = versions.sort(compareVersions).map(version => version.join('.'));
    assert.deepEqual(sorted, ['0.9.0', '0.10.0', '7.3.9', '7.3.10', '7.29.1', '10.0.0']);
  });

  it('does not mutate its arguments', () => {
    const a = [1, 2, 3];
    const b = [1, 2, 4];
    compareVersions(a, b);
    assert.deepEqual(a, [1, 2, 3]);
    assert.deepEqual(b, [1, 2, 4]);
  });
});

describe('planOverride', () => {
  describe('advisories seen in this repository', () => {
    it('plans the proxy-addr fix inside the patched major', () => {
      assert.deepEqual(pickOverride(proxyAddrAdvisory), {
        selector: 'proxy-addr@>=2.0.0 <2.0.8',
        range: '>=2.0.8 <3',
      });
    });

    it('plans the source-map-js fix', () => {
      assert.deepEqual(pickOverride(sourceMapAdvisory), {
        selector: 'source-map-js@>=1.0.0 <1.2.2',
        range: '>=1.2.2 <2',
      });
    });

    it('plans the compression fix from an open-ended vulnerable range', () => {
      assert.deepEqual(pickOverride(compressionAdvisory), {
        selector: 'compression@>=1.0.0 <1.8.2',
        range: '>=1.8.2 <2',
      });
    });

    it('hands the unpatched node-forge advisory to a human with the ignore instructions', () => {
      assert.equal(pickTodo(unpatchedAdvisory), unpatchedTodo);
    });
  });

  describe('selector and range shape', () => {
    it('starts the selector at the patched major even when the advisory starts higher', () => {
      const advisory = createAdvisory({
        module_name: 'undici',
        vulnerable_versions: '>=7.5.0 <7.29.1',
        patched_versions: '>=7.29.1',
        findings: [{ version: '7.10.0', paths: [] }],
      });
      assert.deepEqual(pickOverride(advisory), {
        selector: 'undici@>=7.0.0 <7.29.1',
        range: '>=7.29.1 <8',
      });
    });

    it('caps a double-digit major at the next major', () => {
      const advisory = createAdvisory({
        module_name: 'glob',
        patched_versions: '>=11.1.0',
        findings: [{ version: '11.0.3', paths: [] }],
      });
      assert.deepEqual(pickOverride(advisory), {
        selector: 'glob@>=11.0.0 <11.1.0',
        range: '>=11.1.0 <12',
      });
    });

    it('treats a 0.x minor as the breaking line', () => {
      const advisory = createAdvisory({
        module_name: 'esbuild',
        vulnerable_versions: '>=0.17.0 <0.28.1',
        patched_versions: '>=0.28.1',
        findings: [{ version: '0.28.0', paths: [] }],
      });
      assert.deepEqual(pickOverride(advisory), {
        selector: 'esbuild@>=0.28.0 <0.28.1',
        range: '>=0.28.1 <0.29.0',
      });
    });

    it('handles a 0.0.x patch', () => {
      const advisory = createAdvisory({
        module_name: 'tiny',
        patched_versions: '>=0.0.5',
        findings: [{ version: '0.0.3', paths: [] }],
      });
      assert.deepEqual(pickOverride(advisory), {
        selector: 'tiny@>=0.0.0 <0.0.5',
        range: '>=0.0.5 <0.1.0',
      });
    });

    it('handles a patch that is the first release after a major', () => {
      const advisory = createAdvisory({
        module_name: 'left',
        patched_versions: '>=3.0.1',
        findings: [{ version: '3.0.0', paths: [] }],
      });
      assert.deepEqual(pickOverride(advisory), {
        selector: 'left@>=3.0.0 <3.0.1',
        range: '>=3.0.1 <4',
      });
    });

    it('exposes the patched version for ordering', () => {
      assert.deepEqual(planOverride(proxyAddrAdvisory).patched, [2, 0, 8]);
    });

    it('returns the status, selector, range and patched version for a fix', () => {
      assert.deepEqual(Object.keys(planOverride(proxyAddrAdvisory)), [
        'status',
        'selector',
        'range',
        'patched',
      ]);
    });

    it('never produces a range that reaches the next major', () => {
      const patches = ['1.0.1', '2.0.8', '7.29.1', '10.2.3', '99.99.99'];
      for (const patch of patches) {
        const [major, minor, release] = parseVersion(patch);
        const plan = planOverride(
          createAdvisory({
            patched_versions: `>=${patch}`,
            findings: [{ version: `${major}.${minor}.${release - 1}`, paths: [] }],
          })
        );
        assert.equal(plan.range, `>=${patch} <${major + 1}`);
      }
    });
  });

  describe('package names', () => {
    const names = [
      'a',
      'ws',
      'proxy-addr',
      'source-map-js',
      'lodash.get',
      'is_js',
      'node-forge',
      'base64-js',
      '7zip-min',
      '@xmldom/xmldom',
      '@babel/plugin-transform-modules-systemjs',
      '@scope.with-dots/pkg_name.js',
    ];
    for (const name of names) {
      it(`accepts ${name}`, () => {
        const plan = planOverride(createAdvisory({ module_name: name }));
        assert.equal(plan.selector, `${name}@>=2.0.0 <2.0.8`);
      });
    }

    const rejected = [
      '',
      ' ',
      'Proxy-Addr',
      'proxy addr',
      'proxy-addr@1',
      'proxy-addr@>=1 <2',
      'express>proxy-addr',
      '../proxy-addr',
      './proxy-addr',
      '.proxy-addr',
      '_proxy-addr',
      '@scope',
      '@scope/',
      '@/pkg',
      '@scope/pkg/extra',
      'proxy-addr"',
      'proxy-addr\n',
      'proxy-addr`',
      'proxy-addr$(id)',
      'proxy-addr || evil',
    ];
    for (const name of rejected) {
      it(`rejects ${JSON.stringify(name)} without echoing it`, () => {
        const todo = pickTodo(createAdvisory({ module_name: name }));
        assert.equal(
          todo,
          'The advisory names a package this script does not recognise. Check it by hand.'
        );
      });
    }

    it('rejects an advisory without a package name', () => {
      const { module_name: removed, ...advisory } = proxyAddrAdvisory;
      assert.equal(removed, 'proxy-addr');
      assert.match(pickTodo(advisory), /does not recognise/);
    });
  });

  describe('patched versions', () => {
    const accepted = ['>=2.0.8', '>= 2.0.8', '  >=2.0.8  ', '>=2.0.8\n'];
    for (const patched of accepted) {
      it(`accepts ${JSON.stringify(patched)}`, () => {
        assert.deepEqual(pickOverride(createAdvisory({ patched_versions: patched })), {
          selector: 'proxy-addr@>=2.0.0 <2.0.8',
          range: '>=2.0.8 <3',
        });
      });
    }

    const missing = ['', '   ', '<0.0.0', '< 0.0.0', ' <0.0.0\n'];
    for (const patched of missing) {
      it(`treats ${JSON.stringify(patched)} as no fixed release`, () => {
        const todo = pickTodo(createAdvisory({ patched_versions: patched }));
        assert.match(todo, /^No fixed release exists\./);
        assert.match(todo, /add `GHSA-jqcg-44mw-7w3h` to `auditConfig\.ignoreGhsas`/);
        assert.match(todo, /`pnpm-workspace\.yaml`/);
      });
    }

    it('treats a missing patched version field as no fixed release', () => {
      const { patched_versions: removed, ...advisory } = proxyAddrAdvisory;
      assert.equal(removed, '>=2.0.8');
      assert.match(pickTodo(advisory), /^No fixed release exists\./);
    });

    const complex = [
      '2.0.8',
      '>2.0.7',
      '^2.0.8',
      '~2.0.8',
      '>=2.0',
      '>=2',
      '>=2.0.8-rc.1',
      '>=2.0.8 <3',
      '>=2.0.8 <3.0.0',
      '>=1.2.5 <2.0.0 || >=2.3.1',
      '>=2.0.8 || >=3.0.1',
      '*',
      'none',
    ];
    for (const patched of complex) {
      it(`asks a human to pick a release for ${JSON.stringify(patched)}`, () => {
        const todo = pickTodo(createAdvisory({ patched_versions: patched }));
        assert.ok(todo.startsWith(`The patched range \`${patched}\` is not a single version.`));
        assert.match(todo, /`pnpm\.overrides` in `package\.json`/);
      });
    }
  });

  describe('installed versions', () => {
    function advisoryWith(versions) {
      return createAdvisory({ findings: versions.map(version => ({ version, paths: [] })) });
    }

    const covered = [
      ['the lowest version of the major', ['2.0.0']],
      ['the version just below the patch', ['2.0.7']],
      ['several versions inside the major', ['2.0.0', '2.0.3', '2.0.7']],
      ['the same version reported twice', ['2.0.7', '2.0.7']],
      ['a version at or above the patch in the same major', ['2.0.8', '2.9.0']],
    ];
    for (const [label, versions] of covered) {
      it(`plans a fix for ${label}`, () => {
        assert.deepEqual(pickOverride(advisoryWith(versions)), {
          selector: 'proxy-addr@>=2.0.0 <2.0.8',
          range: '>=2.0.8 <3',
        });
      });
    }

    const uncovered = [
      ['an older major', ['1.1.0'], '1.1.0'],
      ['the last release of the previous major', ['1.99.99'], '1.99.99'],
      ['a newer major', ['3.0.0'], '3.0.0'],
      ['a prerelease', ['2.0.0-rc.1'], '2.0.0-rc.1'],
      ['an unparseable version', ['latest'], 'latest'],
      ['a mix of covered and older-major versions', ['2.0.7', '1.1.0'], '1.1.0'],
      ['two versions outside the major', ['1.1.0', '3.0.0'], '1.1.0, 3.0.0'],
      ['the same outside version twice', ['1.1.0', '1.1.0'], '1.1.0'],
    ];
    for (const [label, versions, listed] of uncovered) {
      it(`refuses ${label} and names what is installed`, () => {
        const todo = pickTodo(advisoryWith(versions));
        assert.ok(
          todo.startsWith(`Installed ${listed} is outside the patched release line \`>=2.0.8 <3\``),
          todo
        );
      });
    }

    it('gives the exact cross-major override to add', () => {
      assert.equal(pickTodo(crossMajorAdvisory), crossMajorTodo);
    });

    it('refuses a 0.x install from a different minor', () => {
      const todo = pickTodo(
        createAdvisory({
          module_name: 'esbuild',
          patched_versions: '>=0.28.1',
          findings: [{ version: '0.27.9', paths: [] }],
        })
      );
      assert.match(
        todo,
        /Installed 0\.27\.9 is outside the patched release line `>=0\.28\.1 <0\.29\.0`/
      );
      assert.match(todo, /`"esbuild@<0\.28\.1": ">=0\.28\.1 <0\.29\.0"`/);
    });

    it('refuses to plan when no findings are listed, and offers the entry to add by hand', () => {
      assert.equal(
        pickTodo(createAdvisory({ findings: [] })),
        'The audit lists no installed version, so the script cannot tell whether a same-major ' +
          'fix applies. Check `pnpm why proxy-addr`, then add ' +
          '`"proxy-addr@>=2.0.0 <2.0.8": ">=2.0.8 <3"` to `pnpm.overrides` if every installed ' +
          'copy is in that release line.'
      );
    });

    it('refuses to plan when the findings field is missing', () => {
      const { findings: removed, ...advisory } = proxyAddrAdvisory;
      assert.equal(removed.length, 1);
      assert.match(pickTodo(advisory), /^The audit lists no installed version/);
    });

    it('reports a missing patch before missing findings', () => {
      const todo = pickTodo(createAdvisory({ patched_versions: '<0.0.0', findings: [] }));
      assert.match(todo, /^No fixed release exists\./);
    });
  });

  it('ignores the vulnerable range text entirely', () => {
    const ranges = ['', '<2.0.8', '>=1.1.0 <2.0.8', '<1.0.0 || >=2.0.0 <2.0.8', 'garbage'];
    for (const range of ranges) {
      assert.deepEqual(pickOverride(createAdvisory({ vulnerable_versions: range })), {
        selector: 'proxy-addr@>=2.0.0 <2.0.8',
        range: '>=2.0.8 <3',
      });
    }
  });

  it('does not mutate the advisory', () => {
    const advisory = structuredClone(proxyAddrAdvisory);
    planOverride(advisory);
    assert.deepEqual(advisory, proxyAddrAdvisory);
  });
});

describe('compareFixes', () => {
  function createUndiciFix(patch, installed) {
    return createFix(
      createAdvisory({
        id: Number(patch.replaceAll('.', '')),
        module_name: 'undici',
        patched_versions: `>=${patch}`,
        findings: [{ version: installed, paths: [] }],
      })
    );
  }

  it('orders fixes by package name', () => {
    const fixes = [sourceMapAdvisory, proxyAddrAdvisory, compressionAdvisory].map(createFix);
    assert.deepEqual(
      fixes.sort(compareFixes).map(fix => fix.advisory.module_name),
      ['compression', 'proxy-addr', 'source-map-js']
    );
  });

  it('puts the highest patch of one package last so it wins in pnpm', () => {
    const fixes = [
      createUndiciFix('7.30.0', '7.10.0'),
      createUndiciFix('7.29.1', '7.10.0'),
      createUndiciFix('7.3.5', '7.3.0'),
    ];
    assert.deepEqual(
      fixes.sort(compareFixes).map(fix => fix.plan.range),
      ['>=7.3.5 <8', '>=7.29.1 <8', '>=7.30.0 <8']
    );
  });

  it('orders majors of one package numerically', () => {
    const fixes = [
      createUndiciFix('10.0.1', '10.0.0'),
      createUndiciFix('6.28.1', '6.20.0'),
      createUndiciFix('7.29.1', '7.10.0'),
    ];
    assert.deepEqual(
      fixes.sort(compareFixes).map(fix => fix.plan.selector),
      ['undici@>=6.0.0 <6.28.1', 'undici@>=7.0.0 <7.29.1', 'undici@>=10.0.0 <10.0.1']
    );
  });

  it('treats identical fixes as equal', () => {
    assert.equal(compareFixes(createFix(proxyAddrAdvisory), createFix(proxyAddrAdvisory)), 0);
  });
});

describe('mergeOverrides', () => {
  const manifest = {
    name: 'leather-mono',
    version: '2.7.2',
    scripts: { build: 'turbo run build' },
    pnpm: {
      overrides: {
        'levelup>semver': '5.7.2',
        glob: '11.1.0',
        'undici@>=7.0.0 <7.29.1': '>=7.29.1 <8',
      },
      patchedDependencies: { 'pofile@1.1.4': 'patches/pofile@1.1.4.patch' },
    },
    engines: { node: '>=22.15.0' },
  };

  it('appends new selectors after every existing entry so they win in pnpm', () => {
    const merged = mergeOverrides(manifest, [
      createFix(compressionAdvisory),
      createFix(proxyAddrAdvisory),
    ]);
    assert.deepEqual(Object.entries(merged.pnpm.overrides), [
      ['levelup>semver', '5.7.2'],
      ['glob', '11.1.0'],
      ['undici@>=7.0.0 <7.29.1', '>=7.29.1 <8'],
      ['compression@>=1.0.0 <1.8.2', '>=1.8.2 <2'],
      ['proxy-addr@>=2.0.0 <2.0.8', '>=2.0.8 <3'],
    ]);
  });

  it('keeps the order in which fixes are given', () => {
    const merged = mergeOverrides({ pnpm: { overrides: {} } }, [
      createFix(sourceMapAdvisory),
      createFix(compressionAdvisory),
    ]);
    assert.deepEqual(Object.keys(merged.pnpm.overrides), [
      'source-map-js@>=1.0.0 <1.2.2',
      'compression@>=1.0.0 <1.8.2',
    ]);
  });

  it('keeps other pnpm settings and top-level fields in place', () => {
    const merged = mergeOverrides(manifest, [createFix(proxyAddrAdvisory)]);
    assert.deepEqual(Object.keys(merged), ['name', 'version', 'scripts', 'pnpm', 'engines']);
    assert.deepEqual(Object.keys(merged.pnpm), ['overrides', 'patchedDependencies']);
    assert.deepEqual(merged.pnpm.patchedDependencies, manifest.pnpm.patchedDependencies);
    assert.deepEqual(merged.scripts, manifest.scripts);
    assert.deepEqual(merged.engines, manifest.engines);
  });

  it('writes only the selector and range, never the plan internals', () => {
    const merged = mergeOverrides({}, [createFix(proxyAddrAdvisory)]);
    assert.deepEqual(merged.pnpm.overrides, { 'proxy-addr@>=2.0.0 <2.0.8': '>=2.0.8 <3' });
  });

  it('creates the overrides map when pnpm has none', () => {
    const merged = mergeOverrides({ pnpm: { patchedDependencies: {} } }, [
      createFix(proxyAddrAdvisory),
    ]);
    assert.deepEqual(merged.pnpm, {
      patchedDependencies: {},
      overrides: { 'proxy-addr@>=2.0.0 <2.0.8': '>=2.0.8 <3' },
    });
  });

  it('creates the pnpm field when the manifest has none', () => {
    const merged = mergeOverrides({ name: 'x' }, [createFix(proxyAddrAdvisory)]);
    assert.deepEqual(merged, {
      name: 'x',
      pnpm: { overrides: { 'proxy-addr@>=2.0.0 <2.0.8': '>=2.0.8 <3' } },
    });
  });

  it('replaces the value of a selector that already exists without duplicating it', () => {
    const existing = {
      pnpm: { overrides: { 'proxy-addr@>=2.0.0 <2.0.8': '2.0.8', glob: '11.1.0' } },
    };
    const merged = mergeOverrides(existing, [createFix(proxyAddrAdvisory)]);
    assert.deepEqual(Object.entries(merged.pnpm.overrides), [
      ['proxy-addr@>=2.0.0 <2.0.8', '>=2.0.8 <3'],
      ['glob', '11.1.0'],
    ]);
  });

  it('collapses two advisories that plan the same selector', () => {
    const second = createAdvisory({ id: 2, github_advisory_id: 'GHSA-aaaa-bbbb-cccc' });
    const merged = mergeOverrides({}, [createFix(proxyAddrAdvisory), createFix(second)]);
    assert.deepEqual(Object.keys(merged.pnpm.overrides), ['proxy-addr@>=2.0.0 <2.0.8']);
  });

  it('keeps separate selectors for two patches of one package', () => {
    const later = createAdvisory({ id: 2, patched_versions: '>=2.0.9' });
    const merged = mergeOverrides({}, [createFix(proxyAddrAdvisory), createFix(later)]);
    assert.deepEqual(merged.pnpm.overrides, {
      'proxy-addr@>=2.0.0 <2.0.8': '>=2.0.8 <3',
      'proxy-addr@>=2.0.0 <2.0.9': '>=2.0.9 <3',
    });
  });

  it('leaves the overrides untouched when there is nothing to add', () => {
    assert.deepEqual(mergeOverrides(manifest, []), manifest);
  });

  it('does not mutate the manifest it is given', () => {
    const original = structuredClone(manifest);
    mergeOverrides(manifest, [createFix(proxyAddrAdvisory)]);
    assert.deepEqual(manifest, original);
  });

  it('extends the real root manifest without disturbing its existing overrides', () => {
    const rootManifest = JSON.parse(readFileSync(rootManifestPath, 'utf8'));
    const existing = Object.entries(rootManifest.pnpm.overrides);
    const merged = mergeOverrides(rootManifest, [
      createFix(createAdvisory({ module_name: 'audit-fix-spec-probe' })),
    ]);
    const entries = Object.entries(merged.pnpm.overrides);

    assert.deepEqual(entries.slice(0, existing.length), existing);
    assert.deepEqual(entries.at(-1), ['audit-fix-spec-probe@>=2.0.0 <2.0.8', '>=2.0.8 <3']);
    assert.equal(entries.length, existing.length + 1);
  });

  it('round-trips the real root manifest byte for byte when nothing is added', () => {
    const text = readFileSync(rootManifestPath, 'utf8');
    assert.equal(`${JSON.stringify(mergeOverrides(JSON.parse(text), []), null, 2)}\n`, text);
  });
});

describe('describeInstallFailure', () => {
  const fix = createFix(compressionAdvisory);

  it('explains a release blocked by minimumReleaseAge and how to ship it anyway', () => {
    assert.equal(
      describeInstallFailure(`Progress: resolved 1\n ${immatureError}\n`, fix),
      'The fixed release is newer than `minimumReleaseAge` allows, so later runs retry it ' +
        'automatically. To ship it now, add `compression` to `minimumReleaseAgeExclude` in ' +
        '`pnpm-workspace.yaml` and `"compression@>=1.0.0 <1.8.2": ">=1.8.2 <2"` to ' +
        '`pnpm.overrides` in `package.json`.'
    );
  });

  it('explains an unpublished fix and the ignore route', () => {
    assert.equal(
      describeInstallFailure(` ${unpublishedError}\n`, fix),
      'The fixed release is not on npm: no published version satisfies `>=1.8.2 <2`. Wait for ' +
        'it, or if the package never runs in a shipped app, add `GHSA-vc2v-76pw-4v95` to ' +
        '`auditConfig.ignoreGhsas` in `pnpm-workspace.yaml` with a comment saying why it is not ' +
        'exploitable and when to remove the entry.'
    );
  });

  it('does not confuse the two pnpm error codes', () => {
    assert.match(describeInstallFailure(immatureError, fix), /minimumReleaseAge/);
    assert.doesNotMatch(describeInstallFailure(immatureError, fix), /not on npm/);
    assert.match(describeInstallFailure(unpublishedError, fix), /not on npm/);
    assert.doesNotMatch(describeInstallFailure(unpublishedError, fix), /minimumReleaseAgeExclude/);
  });

  it('quotes any other pnpm error with the entry it rejected', () => {
    assert.equal(
      describeInstallFailure(`Scope: all 28 workspace projects\n ${registryError}\nmore\n`, fix),
      '`pnpm install` rejected `"compression@>=1.0.0 <1.8.2": ">=1.8.2 <2"`: ' +
        `\`${registryError}\`. Resolve it by hand.`
    );
  });

  it('falls back to the last line when pnpm prints no error code', () => {
    const todo = describeInstallFailure('first line\n\nKilled\n\n', fix);
    assert.match(todo, /: `Killed`\. Resolve it by hand\.$/);
  });

  it('keeps package names from the error inside one code span', () => {
    const todo = describeInstallFailure(
      'ERR_PNPM_FETCH_404  GET @evil/pkg `[click](https://evil.test)` failed',
      fix
    );
    assert.match(
      todo,
      /: `ERR_PNPM_FETCH_404 {2}GET @evil\/pkg \[click\]\(https:\/\/evil\.test\) failed`\. Resolve it by hand\.$/
    );
  });

  it('copes with empty output', () => {
    assert.match(describeInstallFailure('', fix), /: no output\. Resolve it by hand\.$/);
    assert.match(describeInstallFailure('\n\n', fix), /: no output\. Resolve it by hand\.$/);
  });

  it('truncates a very long error line', () => {
    const todo = describeInstallFailure(`ERR_PNPM_UNEXPECTED ${'x'.repeat(5000)}`, fix);
    assert.ok(todo.length < 500);
    assert.match(todo, /ERR_PNPM_UNEXPECTED x+`\. Resolve it by hand\.$/);
  });
});

describe('findDroppedVersions', () => {
  const fix = createFix(compressionAdvisory);
  function lockfileWith(keys) {
    return ["lockfileVersion: '9.0'", '', 'packages:', '', ...keys.map(key => `  ${key}:`)].join(
      '\n'
    );
  }

  it('allows the vulnerable copy to move up inside the release line', () => {
    const before = lockfileWith(['compression@1.8.1', 'compression@3.0.0']);
    const after = lockfileWith(['compression@1.8.2', 'compression@3.0.0']);
    assert.deepEqual(findDroppedVersions(before, after, fix), []);
  });

  it('flags a copy outside the release line that the override replaced', () => {
    const before = lockfileWith(['compression@1.8.1', 'compression@3.0.0', 'compression@0.9.0']);
    const after = lockfileWith(['compression@1.8.2']);
    assert.deepEqual(findDroppedVersions(before, after, fix), ['3.0.0', '0.9.0']);
  });

  it('reads quoted scoped keys and snapshot keys with peer suffixes', () => {
    const scoped = createFix(createAdvisory({ module_name: '@scope/pkg' }));
    const before = lockfileWith(["'@scope/pkg@3.1.0(react@18.0.0)'", "'@scope/pkg@2.0.7'"]);
    const after = lockfileWith(["'@scope/pkg@2.0.8'"]);
    assert.deepEqual(findDroppedVersions(before, after, scoped), ['3.1.0']);
  });

  it('ignores packages whose name only starts with the advisory name', () => {
    const before = lockfileWith(['compression-extra@3.0.0', 'compression@1.8.1']);
    const after = lockfileWith(['compression@1.8.2']);
    assert.deepEqual(findDroppedVersions(before, after, fix), []);
  });

  it('ignores dependency entries nested below a key', () => {
    const before = `${lockfileWith(['compression@1.8.1'])}\n    compression@3.0.0: {}`;
    assert.deepEqual(findDroppedVersions(before, lockfileWith(['compression@1.8.2']), fix), []);
  });
});

describe('describeDroppedVersions', () => {
  it('names the entry, the replaced versions and pnpm why', () => {
    assert.equal(
      describeDroppedVersions(['3.0.0'], createFix(compressionAdvisory)),
      '`"compression@>=1.0.0 <1.8.2": ">=1.8.2 <2"` also replaced installed 3.0.0, which is ' +
        'outside the patched release line, so it was rolled back. Narrow the override to the ' +
        'vulnerable dependents after checking `pnpm why compression`.'
    );
  });
});

describe('describeStillReported', () => {
  it('names the entry and points at pnpm why', () => {
    assert.equal(
      describeStillReported(createFix(compressionAdvisory)),
      '`"compression@>=1.0.0 <1.8.2": ">=1.8.2 <2"` was added but the advisory is still ' +
        'reported, so another override or a pinned parent takes precedence. Check ' +
        '`pnpm why compression`.'
    );
  });
});

describe('buildReport', () => {
  const unpatchedItem = { advisory: unpatchedAdvisory, todo: unpatchedTodo };

  it('is only the header when nothing was fixed or left over', () => {
    assert.equal(buildReport([], []), `${reportHeader}\n`);
  });

  it('lists added overrides with a link, the severity and the exact entry', () => {
    assert.equal(
      buildReport([createFix(proxyAddrAdvisory)], []),
      [
        reportHeader,
        '',
        '## Overrides added',
        '',
        '- `proxy-addr` [GHSA-jqcg-44mw-7w3h](https://github.com/advisories/GHSA-jqcg-44mw-7w3h) (critical): `"proxy-addr@>=2.0.0 <2.0.8": ">=2.0.8 <3"`',
        '',
      ].join('\n')
    );
  });

  it('turns leftovers into a checklist that says what to do', () => {
    assert.equal(
      buildReport([], [unpatchedItem]),
      [
        reportHeader,
        '',
        nothingFixedNote,
        '',
        '## Needs a human',
        '',
        todoIntro,
        '',
        '- [ ] `node-forge` [GHSA-86w9-cpqp-85rv](https://github.com/advisories/GHSA-86w9-cpqp-85rv) (high), installed 1.4.0, reached through `apps__mobile>expo>@expo/cli>node-forge`',
        `  ${unpatchedTodo}`,
        '',
      ].join('\n')
    );
  });

  it('says the pull request is empty only when nothing was fixed', () => {
    assert.match(buildReport([], [unpatchedItem]), /this pull request has no changes\./);
    assert.doesNotMatch(
      buildReport([createFix(proxyAddrAdvisory)], [unpatchedItem]),
      /this pull request has no changes\./
    );
    assert.doesNotMatch(
      buildReport([createFix(proxyAddrAdvisory)], []),
      /this pull request has no changes\./
    );
  });

  it('puts added overrides before the checklist', () => {
    const report = buildReport([createFix(proxyAddrAdvisory)], [unpatchedItem]);
    assert.ok(report.indexOf('## Overrides added') < report.indexOf('## Needs a human'));
    assert.match(report, /">=2\.0\.8 <3"`\n\n## Needs a human\n\n/);
  });

  it('counts the other dependency paths instead of listing them', () => {
    const report = buildReport([], [{ advisory: sourceMapAdvisory, todo: 'Do it.' }]);
    assert.match(
      report,
      /installed 1\.2\.1, reached through `apps__extension>mixpanel-browser>@mixpanel\/rrweb>postcss>source-map-js` \(\+2 more\)\n {2}Do it\.\n$/
    );
  });

  it('lists every installed version once', () => {
    const advisory = createAdvisory({
      findings: [
        { version: '1.1.0', paths: ['a>proxy-addr'] },
        { version: '1.2.0', paths: ['b>proxy-addr'] },
        { version: '1.1.0', paths: ['c>proxy-addr'] },
      ],
    });
    assert.match(
      buildReport([], [{ advisory, todo: 'Do it.' }]),
      /\(critical\), installed 1\.1\.0, 1\.2\.0, reached through `a>proxy-addr` \(\+2 more\)\n/
    );
  });

  it('leaves out the context when the advisory has no findings', () => {
    const { findings: removed, ...advisory } = proxyAddrAdvisory;
    assert.equal(removed.length, 1);
    assert.match(buildReport([], [{ advisory, todo: 'Do it.' }]), /\(critical\)\n {2}Do it\.\n$/);
  });

  it('shows installed versions without paths when none are listed', () => {
    const advisory = createAdvisory({ findings: [{ version: '2.0.7' }] });
    assert.match(
      buildReport([], [{ advisory, todo: 'Do it.' }]),
      /\(critical\), installed 2\.0\.7\n {2}Do it\.\n$/
    );
  });

  it('keeps one checklist item per advisory in the order given', () => {
    const report = buildReport(
      [],
      [
        { advisory: unpatchedAdvisory, todo: 'First.' },
        { advisory: crossMajorAdvisory, todo: 'Second.' },
        { advisory: compressionAdvisory, todo: 'Third.' },
      ]
    );
    const items = report.split('\n').filter(line => line.startsWith('- [ ] '));
    assert.deepEqual(
      items.map(line => line.split('`')[1]),
      ['node-forge', 'proxy-addr', 'compression']
    );
    assert.deepEqual(
      report.split('\n').filter(line => line.startsWith('  ')),
      ['  First.', '  Second.', '  Third.']
    );
  });

  it('omits a heading that has no items', () => {
    assert.doesNotMatch(buildReport([createFix(proxyAddrAdvisory)], []), /Needs a human/);
    assert.doesNotMatch(buildReport([], [unpatchedItem]), /Overrides added/);
  });

  it('ends with exactly one newline', () => {
    const reports = [
      buildReport([], []),
      buildReport([createFix(proxyAddrAdvisory)], []),
      buildReport([], [unpatchedItem]),
      buildReport([createFix(proxyAddrAdvisory)], [unpatchedItem]),
    ];
    for (const report of reports) {
      assert.ok(report.endsWith('\n'));
      assert.ok(!report.endsWith('\n\n'));
    }
  });

  describe('untrusted advisory fields', () => {
    function reportFor(overrides) {
      return buildReport([], [{ advisory: createAdvisory(overrides), todo: 'Do it.' }]);
    }

    it('builds the link from the advisory id and ignores the url field', () => {
      const report = reportFor({ url: 'https://evil.example/x) [click](https://evil.example' });
      assert.match(
        report,
        /`proxy-addr` \[GHSA-jqcg-44mw-7w3h\]\(https:\/\/github\.com\/advisories\/GHSA-jqcg-44mw-7w3h\) \(critical\)/
      );
      assert.doesNotMatch(report, /evil/);
    });

    const badIds = [
      'GHSA-jqcg-44mw-7w3h](https://evil.example)',
      'GHSA-jqcg-44mw',
      'ghsa-jqcg-44mw-7w3h',
      'CVE-2026-0001',
      'GHSA-jqcg-44mw-7w3h\n# heading',
      '',
    ];
    for (const id of badIds) {
      it(`does not link an advisory id like ${JSON.stringify(id)}`, () => {
        const report = reportFor({ github_advisory_id: id });
        assert.match(report, /- \[ \] `proxy-addr` unidentified advisory \(critical\)/);
        assert.doesNotMatch(report, /evil|heading|\]\(/);
      });
    }

    it('does not link an advisory with no id field', () => {
      const { github_advisory_id: removed, ...advisory } = proxyAddrAdvisory;
      assert.equal(removed, 'GHSA-jqcg-44mw-7w3h');
      assert.match(
        buildReport([], [{ advisory, todo: 'Do it.' }]),
        /`proxy-addr` unidentified advisory \(critical\)/
      );
    });

    const badSeverities = ['High', 'high) [x](https://evil.example', 'high\n# heading', '', 7];
    for (const severity of badSeverities) {
      it(`replaces a severity like ${JSON.stringify(severity)}`, () => {
        const report = reportFor({ severity });
        assert.match(report, /\(unknown\), installed 2\.0\.7/);
        assert.doesNotMatch(report, /evil|heading/);
      });
    }

    it('replaces a missing severity', () => {
      const { severity: removed, ...advisory } = proxyAddrAdvisory;
      assert.equal(removed, 'critical');
      assert.match(buildReport([], [{ advisory, todo: 'Do it.' }]), /\(unknown\), installed/);
    });

    it('strips backticks and newlines from the dependency path', () => {
      const report = reportFor({
        findings: [
          { version: '2.0.7', paths: ['apps__web>evil`\n# heading\r\n`[x](y)>proxy-addr'] },
        ],
      });
      assert.match(
        report,
        /reached through `apps__web>evil# heading\[x\]\(y\)>proxy-addr`\n {2}Do it\.\n$/
      );
      assert.equal(report.split('\n').filter(line => line.startsWith('#')).length, 1);
    });

    it('strips markdown from an installed version', () => {
      const report = reportFor({
        findings: [{ version: '2.0.7 [x](https://evil.example)\n# heading', paths: [] }],
      });
      assert.match(
        report,
        /\(critical\), installed 2\.0\.7xhttpsevil\.exampleheading\n {2}Do it\.\n$/
      );
      assert.doesNotMatch(report, /installed .*\]\(|\n# heading/);
    });

    it('keeps ordinary prerelease and build versions readable', () => {
      const report = reportFor({
        findings: [{ version: '2.0.0-rc.1+build.5', paths: [] }],
      });
      assert.match(report, /installed 2\.0\.0-rc\.1\+build\.5\n/);
    });
  });
});

describe('untrusted advisory fields in instructions', () => {
  it('strips markdown from installed versions named in the cross-major instruction', () => {
    const plan = planOverride(
      createAdvisory({ findings: [{ version: '1.1.0`\n# heading [x](y)', paths: [] }] })
    );
    assert.equal(plan.status, 'manual');
    assert.match(plan.todo, /^Installed 1\.1\.0headingxy is outside the patched release line/);
    assert.doesNotMatch(plan.todo, /\n/);
  });

  it('strips backticks and newlines from an unusual patched range', () => {
    const plan = planOverride(createAdvisory({ patched_versions: '>=2.0.8 `x`\n# heading' }));
    assert.equal(plan.status, 'manual');
    assert.ok(
      plan.todo.startsWith('The patched range `>=2.0.8 x# heading` is not a single version.')
    );
  });

  it('does not put an invalid advisory id into the ignore instruction', () => {
    const plan = planOverride(
      createAdvisory({ patched_versions: '<0.0.0', github_advisory_id: 'GHSA-x` [y](z)' })
    );
    assert.match(plan.todo, /add its GHSA id to `auditConfig\.ignoreGhsas`/);
    assert.doesNotMatch(plan.todo, /\[y\]/);
  });

  it('uses the same rule in the unpublished-release instruction', () => {
    const fix = createFix(compressionAdvisory);
    const todo = describeInstallFailure(unpublishedError, {
      ...fix,
      advisory: { ...compressionAdvisory, github_advisory_id: 'not-an-id' },
    });
    assert.match(todo, /add its GHSA id to `auditConfig\.ignoreGhsas`/);
  });
});

describe('agreement with the audit-dependencies gate', () => {
  it('runs the same pnpm audit command as repo:code-checks, plus --json', () => {
    const workflow = readFileSync(
      fileURLToPath(new URL('../workflows/repo:code-checks.yml', import.meta.url)),
      'utf8'
    );
    const commands = workflow
      .split('\n')
      .map(line => line.trim())
      .filter(line => line.startsWith('run: pnpm ') && line.includes(' audit '));

    assert.equal(commands.length, 1);
    assert.deepEqual(
      commands[0].replace('run: pnpm ', '').split(' '),
      expectedAuditArgs.filter(argument => argument !== '--json')
    );
  });
});

describe('buildTitle', () => {
  it('falls back to a generic title for no packages', () => {
    assert.equal(buildTitle([]), defaultTitle);
  });

  it('names one package', () => {
    assert.equal(buildTitle(['compression']), 'fix: compression audit');
  });

  it('joins two packages with and', () => {
    assert.equal(
      buildTitle(['compression', 'proxy-addr']),
      'fix: compression and proxy-addr audit'
    );
  });

  it('joins three or more packages with commas and a final and', () => {
    assert.equal(
      buildTitle(['compression', 'proxy-addr', 'source-map-js']),
      'fix: compression, proxy-addr and source-map-js audit'
    );
    assert.equal(buildTitle(['a', 'b', 'c', 'd']), 'fix: a, b, c and d audit');
  });

  it('supports scoped package names', () => {
    assert.equal(buildTitle(['@xmldom/xmldom']), 'fix: @xmldom/xmldom audit');
  });

  it('keeps a title that is exactly at the limit', () => {
    const name = 'x'.repeat(maxTitleLength - 'fix:  audit'.length);
    const title = buildTitle([name]);
    assert.equal(title.length, maxTitleLength);
    assert.equal(title, `fix: ${name} audit`);
  });

  it('falls back when the title is one character over the limit', () => {
    const name = 'x'.repeat(maxTitleLength - 'fix:  audit'.length + 1);
    assert.equal(buildTitle([name]), defaultTitle);
  });

  it('never exceeds the limit however many packages are fixed', () => {
    for (let count = 0; count <= 40; count += 1) {
      const names = Array.from({ length: count }, (_, index) => `package-${index}`);
      const title = buildTitle(names);
      assert.ok(title.length <= maxTitleLength);
      assert.match(title, /^fix: .+ audit$/);
    }
  });

  it('does not mutate the list of names', () => {
    const names = ['b', 'a'];
    buildTitle(names);
    assert.deepEqual(names, ['b', 'a']);
  });
});

describe('audit-fix.mjs command', () => {
  const stubSource = [
    '#!/usr/bin/env node',
    "const fs = require('node:fs');",
    'const args = process.argv.slice(2);',
    "const earlier = fs.readFileSync(process.env.STUB_LOG, 'utf8');",
    "fs.appendFileSync(process.env.STUB_LOG, JSON.stringify({ args, cwd: process.cwd() }) + '\\n');",
    "if (args[0] === 'dlx') {",
    '  const isFollowUp = earlier.includes(\'"dlx"\');',
    '  const source = isFollowUp ? process.env.STUB_AUDIT_FOLLOW_UP : process.env.STUB_AUDIT_STDOUT;',
    '  process.exitCode = Number(process.env.STUB_AUDIT_STATUS);',
    "  process.stdout.write(fs.readFileSync(source, 'utf8'));",
    "} else if (args[0] === 'install') {",
    "  const manifest = JSON.parse(fs.readFileSync('package.json', 'utf8'));",
    '  const selectors = Object.keys(manifest.pnpm.overrides);',
    '  const rejection = JSON.parse(process.env.STUB_INSTALL_REJECT).find(candidate =>',
    "    selectors.some(selector => selector.startsWith(candidate.name + '@'))",
    '  );',
    '  if (rejection) {',
    "    fs.writeFileSync('pnpm-lock.yaml', 'partially written lockfile\\n');",
    '    process.exitCode = 1;',
    '    process.stderr.write(rejection.stderr);',
    '  } else {',
    "    fs.writeFileSync('pnpm-lock.yaml', selectors.map(selector => selector + '\\n').join(''));",
    '  }',
    '} else {',
    '  process.exitCode = 64;',
    '}',
    '',
  ].join('\n');
  const baseManifest = {
    name: 'sandbox',
    private: true,
    pnpm: {
      overrides: { glob: '11.1.0', 'undici@>=7.0.0 <7.29.1': '>=7.29.1 <8' },
      patchedDependencies: { 'pofile@1.1.4': 'patches/pofile@1.1.4.patch' },
    },
  };
  const baseLockfile = "lockfileVersion: '9.0'\n";
  const baseSelectors = ['glob', 'undici@>=7.0.0 <7.29.1'];
  const compressionSelector = 'compression@>=1.0.0 <1.8.2';
  const proxyAddrSelector = 'proxy-addr@>=2.0.0 <2.0.8';
  const sourceMapSelector = 'source-map-js@>=1.0.0 <1.2.2';
  const sandboxes = [];

  after(() => {
    for (const sandbox of sandboxes) rmSync(sandbox.root, { recursive: true, force: true });
  });

  function createSandbox(manifest = baseManifest) {
    const root = realpathSync(mkdtempSync(join(tmpdir(), 'audit-fix-spec-')));
    const repo = join(root, 'repo');
    const bin = join(root, 'bin');
    const script = join(repo, '.github/scripts/audit-fix.mjs');
    const manifestText = `${JSON.stringify(manifest, null, 2)}\n`;
    mkdirSync(join(repo, '.github/scripts'), { recursive: true });
    mkdirSync(bin);
    copyFileSync(scriptPath, script);
    writeFileSync(join(repo, 'package.json'), manifestText);
    writeFileSync(join(repo, 'pnpm-lock.yaml'), baseLockfile);
    writeFileSync(join(bin, 'pnpm'), stubSource, { mode: 0o755 });
    const sandbox = { root, repo, bin, script, manifestText };
    sandboxes.push(sandbox);
    return sandbox;
  }

  function readOptional(path) {
    if (!existsSync(path)) return null;
    return readFileSync(path, 'utf8');
  }

  function lockfileFor(selectors) {
    return selectors.map(selector => `${selector}\n`).join('');
  }

  function runScript(sandbox, options = {}) {
    const logPath = join(sandbox.root, 'pnpm-calls.log');
    const auditPath = join(sandbox.root, 'audit-stdout.txt');
    const followUpPath = join(sandbox.root, 'audit-follow-up.txt');
    const outputPath = join(sandbox.root, 'github-output.txt');
    const githubOutput = options.withoutGithubOutput ? {} : { GITHUB_OUTPUT: outputPath };
    writeFileSync(logPath, '');
    writeFileSync(
      auditPath,
      options.auditStdout ?? JSON.stringify(createAuditReport(options.advisories ?? []))
    );
    writeFileSync(
      followUpPath,
      options.followUpStdout ?? JSON.stringify(createAuditReport(options.stillReported ?? []))
    );
    if (options.existingOutput !== undefined) writeFileSync(outputPath, options.existingOutput);

    const result = spawnSync(process.execPath, [options.scriptArgument ?? sandbox.script], {
      cwd: options.cwd ?? sandbox.repo,
      encoding: 'utf8',
      maxBuffer: maxBufferBytes,
      env: {
        PATH: `${sandbox.bin}${delimiter}${process.env.PATH}`,
        STUB_LOG: logPath,
        STUB_AUDIT_STDOUT: auditPath,
        STUB_AUDIT_FOLLOW_UP: followUpPath,
        STUB_AUDIT_STATUS: String(options.auditStatus ?? 0),
        STUB_INSTALL_REJECT: JSON.stringify(options.reject ?? []),
        ...githubOutput,
      },
    });
    const manifestText = readFileSync(join(sandbox.repo, 'package.json'), 'utf8');
    const calls = readFileSync(logPath, 'utf8')
      .split('\n')
      .filter(line => line !== '')
      .map(line => JSON.parse(line));
    return {
      status: result.status,
      stdout: result.stdout,
      stderr: result.stderr,
      calls,
      commands: calls.map(call => call.args[0]),
      manifestText,
      manifest: JSON.parse(manifestText),
      selectors: Object.keys(JSON.parse(manifestText).pnpm?.overrides ?? {}),
      lockfile: readFileSync(join(sandbox.repo, 'pnpm-lock.yaml'), 'utf8'),
      report: readOptional(join(sandbox.repo, 'tmp/audit-fix-report.md')),
      outputs: readOptional(outputPath),
    };
  }

  describe('when every reported advisory can be fixed', () => {
    const sandbox = createSandbox();
    const run = runScript(sandbox, {
      advisories: [sourceMapAdvisory, proxyAddrAdvisory, compressionAdvisory],
      auditStatus: 1,
    });

    it('exits successfully even though pnpm audit exited with 1', () => {
      assert.equal(run.status, 0, run.stderr);
    });

    it('audits, installs once per override, then audits again to confirm', () => {
      assert.deepEqual(
        run.calls.map(call => call.args),
        [
          expectedAuditArgs,
          expectedInstallArgs,
          expectedInstallArgs,
          expectedInstallArgs,
          expectedAuditArgs,
        ]
      );
    });

    it('runs pnpm from the repository root', () => {
      assert.ok(run.calls.every(call => call.cwd === sandbox.repo));
    });

    it('appends the overrides after the existing ones, sorted by package', () => {
      assert.deepEqual(Object.entries(run.manifest.pnpm.overrides), [
        ['glob', '11.1.0'],
        ['undici@>=7.0.0 <7.29.1', '>=7.29.1 <8'],
        [compressionSelector, '>=1.8.2 <2'],
        [proxyAddrSelector, '>=2.0.8 <3'],
        [sourceMapSelector, '>=1.2.2 <2'],
      ]);
    });

    it('changes nothing else in the manifest', () => {
      const { overrides: written, ...pnpmRest } = run.manifest.pnpm;
      const { overrides: original, ...basePnpmRest } = baseManifest.pnpm;
      assert.equal(Object.keys(written).length, Object.keys(original).length + 3);
      assert.deepEqual(pnpmRest, basePnpmRest);
      assert.deepEqual({ ...run.manifest, pnpm: null }, { ...baseManifest, pnpm: null });
    });

    it('writes the manifest with two-space indentation and a trailing newline', () => {
      assert.equal(run.manifestText, `${JSON.stringify(run.manifest, null, 2)}\n`);
    });

    it('leaves the lockfile from the last install in place', () => {
      assert.equal(
        run.lockfile,
        lockfileFor([...baseSelectors, compressionSelector, proxyAddrSelector, sourceMapSelector])
      );
    });

    it('writes the report used as the pull request body', () => {
      assert.equal(
        run.report,
        [
          reportHeader,
          '',
          '## Overrides added',
          '',
          '- `compression` [GHSA-vc2v-76pw-4v95](https://github.com/advisories/GHSA-vc2v-76pw-4v95) (high): `"compression@>=1.0.0 <1.8.2": ">=1.8.2 <2"`',
          '- `proxy-addr` [GHSA-jqcg-44mw-7w3h](https://github.com/advisories/GHSA-jqcg-44mw-7w3h) (critical): `"proxy-addr@>=2.0.0 <2.0.8": ">=2.0.8 <3"`',
          '- `source-map-js` [GHSA-68fv-2mgg-jv7q](https://github.com/advisories/GHSA-68fv-2mgg-jv7q) (high): `"source-map-js@>=1.0.0 <1.2.2": ">=1.2.2 <2"`',
          '',
        ].join('\n')
      );
    });

    it('prints the same report to stdout', () => {
      assert.equal(run.stdout, run.report);
    });

    it('reports a change, nothing unresolved and a title naming the packages', () => {
      assert.equal(
        run.outputs,
        'changed=true\nunresolved=0\ntitle=fix: compression, proxy-addr and source-map-js audit\n'
      );
    });
  });

  describe('when the audit is clean', () => {
    const sandbox = createSandbox();
    const run = runScript(sandbox, { advisories: [] });

    it('exits successfully', () => {
      assert.equal(run.status, 0, run.stderr);
    });

    it('only runs the audit', () => {
      assert.deepEqual(
        run.calls.map(call => call.args),
        [expectedAuditArgs]
      );
    });

    it('leaves the manifest and lockfile byte for byte as they were', () => {
      assert.equal(run.manifestText, sandbox.manifestText);
      assert.equal(run.lockfile, baseLockfile);
    });

    it('writes a header-only report', () => {
      assert.equal(run.report, `${reportHeader}\n`);
    });

    it('reports nothing to do, so an open pull request can be closed', () => {
      assert.equal(run.outputs, `changed=false\nunresolved=0\ntitle=${defaultTitle}\n`);
    });
  });

  describe('when nothing reported can be fixed', () => {
    const sandbox = createSandbox();
    const run = runScript(sandbox, {
      advisories: [unpatchedAdvisory, crossMajorAdvisory],
      auditStatus: 1,
    });

    it('exits successfully so the pull request can still be opened', () => {
      assert.equal(run.status, 0, run.stderr);
    });

    it('does not run an install or a second audit', () => {
      assert.deepEqual(run.commands, ['dlx']);
    });

    it('leaves the manifest and lockfile untouched', () => {
      assert.equal(run.manifestText, sandbox.manifestText);
      assert.equal(run.lockfile, baseLockfile);
    });

    it('writes a checklist that says what to do for each advisory', () => {
      assert.equal(
        run.report,
        [
          reportHeader,
          '',
          nothingFixedNote,
          '',
          '## Needs a human',
          '',
          todoIntro,
          '',
          '- [ ] `node-forge` [GHSA-86w9-cpqp-85rv](https://github.com/advisories/GHSA-86w9-cpqp-85rv) (high), installed 1.4.0, reached through `apps__mobile>expo>@expo/cli>node-forge`',
          `  ${unpatchedTodo}`,
          '- [ ] `proxy-addr` [GHSA-jqcg-44mw-7w3h](https://github.com/advisories/GHSA-jqcg-44mw-7w3h) (critical), installed 1.1.0, reached through `apps__web>legacy-server>proxy-addr`',
          `  ${crossMajorTodo}`,
          '',
        ].join('\n')
      );
    });

    it('reports no change but two unresolved advisories', () => {
      assert.equal(run.outputs, `changed=false\nunresolved=2\ntitle=${defaultTitle}\n`);
    });
  });

  describe('when some advisories can be fixed and some cannot', () => {
    const sandbox = createSandbox();
    const run = runScript(sandbox, {
      advisories: [compressionAdvisory, unpatchedAdvisory],
      auditStatus: 1,
    });

    it('writes only the fixable override', () => {
      assert.deepEqual(run.selectors, [...baseSelectors, compressionSelector]);
    });

    it('reports both groups without the empty pull request note', () => {
      assert.match(run.report, /## Overrides added\n\n- `compression`/);
      assert.match(run.report, /## Needs a human\n\n.+\n\n- \[ \] `node-forge`/);
      assert.doesNotMatch(run.report, /this pull request has no changes\./);
    });

    it('names only the fixed package in the title and counts the leftover', () => {
      assert.equal(run.outputs, 'changed=true\nunresolved=1\ntitle=fix: compression audit\n');
    });

    it('installs once and confirms with a second audit', () => {
      assert.deepEqual(run.commands, ['dlx', 'install', 'dlx']);
    });
  });

  describe('when pnpm rejects one override', () => {
    const sandbox = createSandbox();
    const run = runScript(sandbox, {
      advisories: [sourceMapAdvisory, proxyAddrAdvisory, compressionAdvisory],
      auditStatus: 1,
      reject: [{ name: 'compression', stderr: ` ${unpublishedError}\n` }],
    });

    it('still succeeds', () => {
      assert.equal(run.status, 0, run.stderr);
    });

    it('rolls the rejected override out of the manifest and keeps the others', () => {
      assert.deepEqual(run.selectors, [...baseSelectors, proxyAddrSelector, sourceMapSelector]);
    });

    it('restores the lockfile the failed install left half written', () => {
      assert.equal(
        run.lockfile,
        lockfileFor([...baseSelectors, proxyAddrSelector, sourceMapSelector])
      );
      assert.doesNotMatch(run.lockfile, /partially written/);
    });

    it('tries every override once', () => {
      assert.deepEqual(run.commands, ['dlx', 'install', 'install', 'install', 'dlx']);
    });

    it('explains the rejected fix in the checklist', () => {
      assert.match(
        run.report,
        /## Overrides added\n\n- `proxy-addr` .+\n- `source-map-js` .+\n\n## Needs a human/
      );
      assert.match(
        run.report,
        /- \[ \] `compression` \[GHSA-vc2v-76pw-4v95\]\(.+\) \(high\), installed 1\.8\.1, reached through `apps__mobile>expo>@expo\/cli>compression`\n {2}The fixed release is not on npm: no published version satisfies `>=1\.8\.2 <2`\./
      );
      assert.match(run.report, /add `GHSA-vc2v-76pw-4v95` to `auditConfig\.ignoreGhsas`/);
    });

    it('names only what was fixed and counts the rejected one', () => {
      assert.equal(
        run.outputs,
        'changed=true\nunresolved=1\ntitle=fix: proxy-addr and source-map-js audit\n'
      );
    });
  });

  describe('when the first override is rejected', () => {
    const sandbox = createSandbox();
    const run = runScript(sandbox, {
      advisories: [compressionAdvisory, proxyAddrAdvisory],
      reject: [{ name: 'compression', stderr: immatureError }],
    });

    it('applies the later override on top of the original files', () => {
      assert.deepEqual(run.selectors, [...baseSelectors, proxyAddrSelector]);
      assert.equal(run.lockfile, lockfileFor([...baseSelectors, proxyAddrSelector]));
    });

    it('explains the release-age block and how to ship the fix anyway', () => {
      assert.match(
        run.report,
        /newer than `minimumReleaseAge` allows, so later runs retry it automatically/
      );
      assert.match(
        run.report,
        /add `compression` to `minimumReleaseAgeExclude` in `pnpm-workspace\.yaml`/
      );
      assert.match(
        run.report,
        /`"compression@>=1\.0\.0 <1\.8\.2": ">=1\.8\.2 <2"` to `pnpm\.overrides`/
      );
    });
  });

  describe('when pnpm rejects every override', () => {
    const sandbox = createSandbox();
    const run = runScript(sandbox, {
      advisories: [compressionAdvisory, proxyAddrAdvisory],
      auditStatus: 1,
      reject: [
        { name: 'compression', stderr: unpublishedError },
        { name: 'proxy-addr', stderr: registryError },
      ],
    });

    it('still succeeds so the checklist pull request can be opened', () => {
      assert.equal(run.status, 0, run.stderr);
    });

    it('restores the manifest and lockfile byte for byte', () => {
      assert.equal(run.manifestText, sandbox.manifestText);
      assert.equal(run.lockfile, baseLockfile);
    });

    it('skips the confirming audit because nothing was applied', () => {
      assert.deepEqual(run.commands, ['dlx', 'install', 'install']);
    });

    it('explains each failure, quoting an unrecognised pnpm error', () => {
      assert.match(run.report, /this pull request has no changes\./);
      assert.doesNotMatch(run.report, /## Overrides added/);
      assert.match(run.report, /`compression` .+\n {2}The fixed release is not on npm/);
      assert.match(
        run.report,
        /`proxy-addr` .+\n {2}`pnpm install` rejected `"proxy-addr@>=2\.0\.0 <2\.0\.8": ">=2\.0\.8 <3"`: `ERR_PNPM_FETCH_503 {2}GET https:\/\/registry\.npmjs\.org\/compression: Unavailable`\. Resolve it by hand\./
      );
    });

    it('reports no change and two unresolved advisories', () => {
      assert.equal(run.outputs, `changed=false\nunresolved=2\ntitle=${defaultTitle}\n`);
    });
  });

  describe('when an override replaces a copy outside the release line', () => {
    const sandbox = createSandbox();
    const lockfile = "lockfileVersion: '9.0'\n\npackages:\n\n  compression@3.0.0:\n";
    writeFileSync(join(sandbox.repo, 'pnpm-lock.yaml'), lockfile);
    const run = runScript(sandbox, { advisories: [compressionAdvisory, proxyAddrAdvisory] });

    it('rolls that override back and keeps the others', () => {
      assert.deepEqual(run.selectors, [...baseSelectors, proxyAddrSelector]);
    });

    it('explains the rollback in the checklist', () => {
      assert.match(
        run.report,
        /- \[ \] `compression` .+\n {2}`"compression@>=1\.0\.0 <1\.8\.2": ">=1\.8\.2 <2"` also replaced installed 3\.0\.0/
      );
      assert.equal(run.outputs, 'changed=true\nunresolved=1\ntitle=fix: proxy-addr audit\n');
    });
  });

  describe('when an applied override does not clear its advisory', () => {
    const sandbox = createSandbox();
    const run = runScript(sandbox, {
      advisories: [compressionAdvisory, proxyAddrAdvisory],
      stillReported: [compressionAdvisory],
      auditStatus: 1,
    });

    it('keeps the override', () => {
      assert.deepEqual(run.selectors, [...baseSelectors, compressionSelector, proxyAddrSelector]);
    });

    it('lists the advisory as added and as still needing a human', () => {
      assert.match(run.report, /## Overrides added\n\n- `compression` .+\n- `proxy-addr` /);
      assert.match(
        run.report,
        /- \[ \] `compression` .+\n {2}`"compression@>=1\.0\.0 <1\.8\.2": ">=1\.8\.2 <2"` was added but the advisory is still reported/
      );
      assert.match(run.report, /Check `pnpm why compression`\./);
      assert.equal(run.report.split('\n').filter(line => line.startsWith('- [ ] ')).length, 1);
    });

    it('counts it as unresolved', () => {
      assert.equal(
        run.outputs,
        'changed=true\nunresolved=1\ntitle=fix: compression and proxy-addr audit\n'
      );
    });
  });

  describe('when the confirming audit reports something new', () => {
    const run = runScript(createSandbox(), {
      advisories: [compressionAdvisory],
      stillReported: [unpatchedAdvisory],
    });

    it('lists the new advisory for a human instead of dropping it', () => {
      assert.match(
        run.report,
        /- \[ \] `node-forge` .+\n {2}Reported only after the overrides above were applied\./
      );
      assert.equal(run.outputs, 'changed=true\nunresolved=1\ntitle=fix: compression audit\n');
    });
  });

  describe('when one package has several advisories', () => {
    const sandbox = createSandbox();
    const later = createAdvisory({
      id: 1,
      github_advisory_id: 'GHSA-late-0000-0000',
      patched_versions: '>=2.0.9',
    });
    const earlier = createAdvisory({ id: 2 });
    const duplicate = createAdvisory({ id: 3, github_advisory_id: 'GHSA-dupe-0000-0000' });
    const run = runScript(sandbox, { advisories: [later, earlier, duplicate], auditStatus: 1 });

    it('writes the higher patch last so it takes precedence', () => {
      assert.deepEqual(Object.entries(run.manifest.pnpm.overrides).slice(-2), [
        [proxyAddrSelector, '>=2.0.8 <3'],
        ['proxy-addr@>=2.0.0 <2.0.9', '>=2.0.9 <3'],
      ]);
    });

    it('writes one entry for two advisories with the same fix', () => {
      assert.equal(new Set(run.selectors).size, run.selectors.length);
      assert.equal(run.selectors.length, baseSelectors.length + 2);
    });

    it('names the package once in the title', () => {
      assert.equal(run.outputs, 'changed=true\nunresolved=0\ntitle=fix: proxy-addr audit\n');
    });

    it('still lists all three advisories in the report', () => {
      assert.equal(run.report.split('\n').filter(line => line.startsWith('- `')).length, 3);
    });
  });

  describe('when pnpm audit does not return a usable report', () => {
    const cases = [
      ['plain text', 'ERR_PNPM_AUDIT_BAD_RESPONSE  The audit endpoint responded with 503'],
      ['empty output', ''],
      ['an error object', JSON.stringify({ error: { code: 'ERR_PNPM_AUDIT' } })],
      ['a null advisory map', JSON.stringify({ advisories: null })],
      ['a string advisory map', JSON.stringify({ advisories: 'none' })],
    ];
    for (const [label, auditStdout] of cases) {
      it(`fails without touching anything for ${label}`, () => {
        const sandbox = createSandbox();
        const run = runScript(sandbox, { auditStdout, auditStatus: 1 });

        assert.notEqual(run.status, 0);
        assert.equal(run.manifestText, sandbox.manifestText);
        assert.equal(run.lockfile, baseLockfile);
        assert.equal(run.report, null);
        assert.equal(run.outputs, null);
        assert.deepEqual(run.commands, ['dlx']);
      });
    }

    it('explains a report that has no advisory map', () => {
      const run = runScript(createSandbox(), { auditStdout: JSON.stringify({ error: {} }) });
      assert.match(run.stderr, /pnpm audit returned no advisory report \(exit 0\)/);
    });

    it('shows what pnpm printed when the output is not JSON', () => {
      const run = runScript(createSandbox(), {
        auditStdout: 'ERR_PNPM_AUDIT_BAD_RESPONSE  The audit endpoint responded with 503',
        auditStatus: 1,
      });
      assert.match(run.stderr, /pnpm audit returned no advisory report \(exit 1\)/);
      assert.match(
        run.stderr,
        /ERR_PNPM_AUDIT_BAD_RESPONSE {2}The audit endpoint responded with 503/
      );
      assert.doesNotMatch(run.stderr, /SyntaxError/);
    });

    it('leaves a single advisory without findings to a human instead of overriding', () => {
      const { findings: removed, ...withoutFindings } = compressionAdvisory;
      const sandbox = createSandbox();
      const run = runScript(sandbox, { advisories: [withoutFindings], auditStatus: 1 });

      assert.equal(removed.length, 1);
      assert.equal(run.manifestText, sandbox.manifestText);
      assert.deepEqual(run.commands, ['dlx']);
      assert.match(
        run.report,
        /- \[ \] `compression` .+\(high\)\n {2}The audit lists no installed version/
      );
      assert.equal(run.outputs, `changed=false\nunresolved=1\ntitle=${defaultTitle}\n`);
    });

    it('fails without outputs when only the confirming audit is unusable', () => {
      const run = runScript(createSandbox(), {
        advisories: [compressionAdvisory],
        followUpStdout: 'registry unavailable',
      });
      assert.notEqual(run.status, 0);
      assert.equal(run.outputs, null);
      assert.equal(run.report, null);
    });
  });

  describe('workflow outputs', () => {
    it('skips the output file when GITHUB_OUTPUT is not set', () => {
      const run = runScript(createSandbox(), {
        advisories: [compressionAdvisory],
        withoutGithubOutput: true,
      });
      assert.equal(run.status, 0, run.stderr);
      assert.equal(run.outputs, null);
      assert.match(run.report, /## Overrides added/);
    });

    it('appends to an output file that already has content', () => {
      const run = runScript(createSandbox(), {
        advisories: [compressionAdvisory],
        existingOutput: 'earlier=value\n',
      });
      assert.equal(
        run.outputs,
        'earlier=value\nchanged=true\nunresolved=0\ntitle=fix: compression audit\n'
      );
    });

    it('falls back to the generic title when the package list is too long', () => {
      const advisories = Array.from({ length: 12 }, (_, index) =>
        createAdvisory({ id: index + 1, module_name: `package-number-${index}` })
      );
      const run = runScript(createSandbox(), { advisories, auditStatus: 1 });
      assert.equal(run.outputs, `changed=true\nunresolved=0\ntitle=${defaultTitle}\n`);
      assert.equal(run.selectors.length, baseSelectors.length + 12);
    });

    it('writes each output on its own line with no stray whitespace', () => {
      const run = runScript(createSandbox(), {
        advisories: [compressionAdvisory, unpatchedAdvisory],
      });
      assert.deepEqual(run.outputs.split('\n'), [
        'changed=true',
        'unresolved=1',
        'title=fix: compression audit',
        '',
      ]);
    });
  });

  describe('robustness', () => {
    it('creates the pnpm field in a manifest that has none', () => {
      const run = runScript(createSandbox({ name: 'bare', private: true }), {
        advisories: [compressionAdvisory],
      });
      assert.deepEqual(run.manifest, {
        name: 'bare',
        private: true,
        pnpm: { overrides: { [compressionSelector]: '>=1.8.2 <2' } },
      });
    });

    it('targets its own repository whatever the working directory is', () => {
      const sandbox = createSandbox();
      const run = runScript(sandbox, { advisories: [compressionAdvisory], cwd: sandbox.root });
      assert.equal(run.status, 0, run.stderr);
      assert.ok(run.calls.every(call => call.cwd === sandbox.repo));
      assert.ok(run.selectors.includes(compressionSelector));
      assert.equal(existsSync(join(sandbox.root, 'tmp')), false);
    });

    it('runs when invoked through a relative path', () => {
      const sandbox = createSandbox();
      const run = runScript(sandbox, {
        advisories: [compressionAdvisory],
        scriptArgument: '.github/scripts/audit-fix.mjs',
      });
      assert.equal(run.status, 0, run.stderr);
      assert.equal(run.outputs, 'changed=true\nunresolved=0\ntitle=fix: compression audit\n');
    });

    it('parses an audit report far larger than the default process buffer', () => {
      const paths = Array.from(
        { length: 40000 },
        (_, index) => `apps__extension>dependency-${index}>postcss>source-map-js`
      );
      const large = { ...sourceMapAdvisory, findings: [{ version: '1.2.1', paths }] };
      const auditStdout = JSON.stringify(createAuditReport([large]));
      assert.ok(auditStdout.length > 2 * 1024 * 1024);

      const run = runScript(createSandbox(), { auditStdout, auditStatus: 1 });
      assert.equal(run.status, 0, run.stderr);
      assert.equal(run.outputs, 'changed=true\nunresolved=0\ntitle=fix: source-map-js audit\n');
    });

    it('keeps a hostile package name out of the manifest and the report', () => {
      const hostile = createAdvisory({ id: 9, module_name: 'proxy-addr@1 || `evil`' });
      const run = runScript(createSandbox(), { advisories: [hostile, compressionAdvisory] });
      assert.deepEqual(run.selectors, [...baseSelectors, compressionSelector]);
      assert.match(run.report, /names a package this script does not recognise/);
      assert.match(run.report, /- \[ \] `unrecognised package` \[GHSA-jqcg-44mw-7w3h\]/);
      assert.doesNotMatch(run.report, /evil/);
      assert.doesNotMatch(run.manifestText, /evil/);
      assert.equal(run.outputs, 'changed=true\nunresolved=1\ntitle=fix: compression audit\n');
    });

    it('does nothing when the module is only imported', () => {
      const sandbox = createSandbox();
      const logPath = join(sandbox.root, 'import-calls.log');
      writeFileSync(logPath, '');
      const result = spawnSync(
        process.execPath,
        [
          '--input-type=module',
          '-e',
          `await import(${JSON.stringify(pathToFileURL(sandbox.script).href)});`,
        ],
        {
          cwd: sandbox.repo,
          encoding: 'utf8',
          env: { PATH: `${sandbox.bin}${delimiter}${process.env.PATH}`, STUB_LOG: logPath },
        }
      );
      assert.equal(result.status, 0, result.stderr);
      assert.equal(readFileSync(logPath, 'utf8'), '');
      assert.equal(readFileSync(join(sandbox.repo, 'package.json'), 'utf8'), sandbox.manifestText);
    });
  });
});
