appId: io.leather.mobilewallet
---
- launchApp
- runFlow: ../shared/clean-up.yaml
- tapOn:
    id: 'homeSettingsButton'
- tapOn:
    id: 'settingsHelpButton'
- tapOn:
    id: 'settingsSupportButton'
# view the support page in the browser
# fails in CI due to the browser not being available?
# - assertVisible: 'GET SUPPORT'
