appId: io.leather.mobilewallet
---
- launchApp
- runFlow: ../shared/clean-up.yaml
- tapOn:
    id: 'homeSettingsButton'
- tapOn:
    id: 'settingsHelpButton'
- tapOn:
    id: 'settingsGuidesButton'
- assertVisible: 'USER GUIDES'
