import { defineTokens } from '@pandacss/dev';

import { tokens as leatherTokens, zIndices } from '@leather.io/tokens';

import { colors } from './colors';

function transformZIndices(zIndices: Record<string, number>) {
  return Object.fromEntries(Object.entries(zIndices).map(([key, value]) => [key, { value }]));
}

export const tokens = defineTokens({
  ...leatherTokens,
  colors,
  zIndex: transformZIndices(zIndices),
  shadows: {
    elevationLight: {
      value: [
        {
          offsetX: 0,
          offsetY: 12,
          blur: 24,
          spread: 0,
          color: 'rgba(18, 16, 15, 0.08)',
        },
        {
          offsetX: 0,
          offsetY: 4,
          blur: 8,
          spread: 0,
          color: 'rgba(18, 16, 15, 0.08)',
        },
        {
          offsetX: 0,
          offsetY: 0,
          blur: 2,
          spread: 0,
          color: 'rgba(18, 16, 15, 0.12)',
        },
      ],
    },
    // TODO: elevationDark is autogenerated, discuss with designers if this shadow is good for dark mode.
    // Light mode shadow is practically invisible in dark mode.
    elevationDark: {
      value: [
        {
          offsetX: 0,
          offsetY: 12,
          blur: 24,
          spread: 0,
          color: 'rgba(0, 0, 0, 0.25)',
        },
        {
          offsetX: 0,
          offsetY: 4,
          blur: 8,
          spread: 0,
          color: 'rgba(0, 0, 0, 0.25)',
        },
        {
          offsetX: 0,
          offsetY: 0,
          blur: 2,
          spread: 0,
          color: 'rgba(0, 0, 0, 0.35)',
        },
      ],
    },
  },
});
