import { useQuery } from '@tanstack/react-query';

import { bitcoinNetworkModeToCoreNetworkMode } from '@leather.io/bitcoin';
import { createGetBnsNamesOwnedByAddressQueryOptions } from '@leather.io/query';

import { parseIfValidPunycode } from '@app/common/utils';
import { formatAccountName } from '@app/common/utils/format-account-name';
import { getAutogeneratedAccountDisplayName } from '@app/common/utils/get-account-display-name';
import { useBnsV2Client } from '@app/query/stacks/bns/bns-v2-client';
import { useCurrentAccountId } from '@app/store/accounts/account';
import { useAccountNameOverride } from '@app/store/accounts/accounts.selectors';
import { useCurrentStacksAccount } from '@app/store/accounts/blockchain/stacks/stacks-account.hooks';
import { useCurrentNetworkState } from '@app/store/networks/networks.hooks';

export function useCurrentAccountDisplayName() {
  const account = useCurrentStacksAccount();
  const currentAccountId = useCurrentAccountId();
  return useAccountDisplayName({
    address: account?.address ?? '',
    index: account?.accountIndex ?? currentAccountId.accountIndex,
    fingerprint: account?.fingerprint ?? currentAccountId.fingerprint,
  });
}

export function useAccountDisplayName({
  address,
  index,
  fingerprint,
}: {
  index: number;
  address?: string;
  fingerprint: string;
}) {
  const { chain } = useCurrentNetworkState();
  const network = bitcoinNetworkModeToCoreNetworkMode(chain.bitcoin.mode);
  const client = useBnsV2Client();
  const customName = useAccountNameOverride({
    fingerprint: fingerprint,
    accountIndex: index,
  });

  const query = useQuery({
    ...createGetBnsNamesOwnedByAddressQueryOptions({
      address,
      network,
      client,
    }),
    select: resp => {
      if (customName) return customName;
      const names = resp.names ?? [];
      return (
        parseIfValidPunycode(formatAccountName(names[0])) ||
        getAutogeneratedAccountDisplayName(index)
      );
    },
  });

  return {
    ...query,
    data: customName || query.data || getAutogeneratedAccountDisplayName(index),
  };
}
