import { useQuery } from '@tanstack/react-query';

import { bitcoinNetworkModeToCoreNetworkMode } from '@leather.io/bitcoin';
import { createGetBnsNamesOwnedByAddressQueryOptions } from '@leather.io/query';
import { isNumber, isUndefined } from '@leather.io/utils';

import { parseIfValidPunycode } from '@app/common/utils';
import { formatAccountName } from '@app/common/utils/format-account-name';
import { getAutogeneratedAccountDisplayName } from '@app/common/utils/get-account-display-name';
import { useBnsV2Client } from '@app/query/stacks/bns/bns-v2-client';
import {
  useCurrentStacksAccount,
  useCurrentStacksAccountAddress,
} from '@app/store/accounts/blockchain/stacks/stacks-account.hooks';
import { useCurrentNetworkState } from '@app/store/networks/networks.hooks';
import { useCustomAccountName } from '@app/store/settings/account-settings.selectors';

export function useCurrentAccountDisplayName() {
  const account = useCurrentStacksAccount();
  const address = useCurrentStacksAccountAddress();
  const { chain } = useCurrentNetworkState();
  const network = bitcoinNetworkModeToCoreNetworkMode(chain.bitcoin.mode);
  const client = useBnsV2Client();
  const customName = useCustomAccountName({
    fingerprint: account?.fingerprint ?? '',
    accountIndex: account?.accountIndex ?? 0,
  });

  return useQuery({
    ...createGetBnsNamesOwnedByAddressQueryOptions({ address, network, client }),
    select: resp => {
      if (customName) return customName;
      if (isUndefined(account?.accountIndex) && (!account || !isNumber(account?.accountIndex)))
        return 'Account';
      const names = resp.names ?? [];
      if (names.length && names[0]) return parseIfValidPunycode(names[0]);
      return getAutogeneratedAccountDisplayName(account?.accountIndex);
    },
  });
}

export function useAccountDisplayName({
  address,
  index,
  fingerprint,
}: {
  index: number;
  address: string;
  fingerprint?: string;
}) {
  const { chain } = useCurrentNetworkState();
  const network = bitcoinNetworkModeToCoreNetworkMode(chain.bitcoin.mode);
  const client = useBnsV2Client();
  const customName = useCustomAccountName({
    fingerprint: fingerprint ?? '',
    accountIndex: index,
  });

  const query = useQuery({
    ...createGetBnsNamesOwnedByAddressQueryOptions({
      address,
      network,
      client,
    }),
    select: resp => {
      if (customName) return customName;
      const names = resp.names ?? [];
      return (
        parseIfValidPunycode(formatAccountName(names[0])) ||
        getAutogeneratedAccountDisplayName(index)
      );
    },
  });

  return {
    ...query,
    data: customName || query.data || getAutogeneratedAccountDisplayName(index),
  };
}
