import { useQuery } from '@tanstack/react-query';

import { createAccountBnsNamesQueryConfig } from '@leather.io/queries';
import type { AccountBnsName } from '@leather.io/services';
import { createAccountAddresses } from '@leather.io/utils';

import { parseIfValidPunycode } from '@app/common/utils';
import { formatAccountName } from '@app/common/utils/format-account-name';
import { getAutogeneratedAccountDisplayName } from '@app/common/utils/get-account-display-name';
import { useUserSettings } from '@app/hooks/use-user-settings';
import { useCurrentAccountId } from '@app/store/accounts/account';
import { useAccountNameOverride } from '@app/store/accounts/accounts.selectors';
import { useCurrentStacksAccount } from '@app/store/accounts/blockchain/stacks/stacks-account.hooks';

export function useCurrentAccountDisplayName() {
  const account = useCurrentStacksAccount();
  const currentAccountId = useCurrentAccountId();
  return useAccountDisplayName({
    address: account?.address ?? '',
    index: account?.accountIndex ?? currentAccountId.accountIndex,
    fingerprint: account?.fingerprint ?? currentAccountId.fingerprint,
  });
}

export function useAccountDisplayName({
  address,
  index,
  fingerprint,
}: {
  index: number;
  address?: string;
  fingerprint: string;
}) {
  const settings = useUserSettings();
  const customName = useAccountNameOverride({
    fingerprint: fingerprint,
    accountIndex: index,
  });

  const request = {
    account: createAccountAddresses({ fingerprint, accountIndex: index }, [], address),
  };

  const query = useQuery({
    ...createAccountBnsNamesQueryConfig(request, settings),
    enabled: Boolean(address),
    select: (names: AccountBnsName[]) => {
      if (customName) return customName;
      const primaryName = names.find(name => name.isPrimary)?.fullName ?? names[0]?.fullName;
      return (
        parseIfValidPunycode(formatAccountName(primaryName)) ||
        getAutogeneratedAccountDisplayName(index)
      );
    },
  });

  return {
    ...query,
    data: customName || query.data || getAutogeneratedAccountDisplayName(index),
  };
}
