/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/quotes/v1/quote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get Single Route Quote
     * @description Get the best quote for a token swap using AMM strategy parameters. Returns a single optimal route with execution details including strategy, bins traversed, and AMM type.
     */
    post: operations['get_quote_api_quotes_v1_quote_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/v1/quote/multi': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get Multi-Route Quote
     * @description Get all viable routes for a token swap, sorted by best to worst output. Supports AMM strategy parameters for fine-grained control over routing preferences.
     */
    post: operations['get_multi_route_quote_api_quotes_v1_quote_multi_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/v1/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Tokens
     * @description Get list of supported tokens from active pools only. Optionally filter by AMM type.
     */
    get: operations['get_tokens_api_quotes_v1_tokens_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/v1/pools': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Pools
     * @description Get list of available pools with optional filtering
     */
    get: operations['get_pools_api_quotes_v1_pools_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/v1/pools/{pool_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Pool By ID
     * @description Get a single pool's metadata by `pool_id`. Returns unsigned active_bin in responses.
     */
    get: operations['get_pool_by_id_api_quotes_v1_pools__pool_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/v1/pairs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Available Pairs
     * @description Get all reachable output tokens for a given input token. Shows available trading pairs with pool information and AMM types. If output_token is provided, only returns pairs with that specific output token.
     */
    get: operations['get_pairs_api_quotes_v1_pairs_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/v1/bins/{pool_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Pool Bins
     * @description Get all bins for a specific pool with their reserves, prices, and liquidity information. Returns comprehensive bin data for pool analysis.
     */
    get: operations['get_pool_bins_api_quotes_v1_bins__pool_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/v1/bins/{pool_id}/active': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Active Bin
     * @description Get detailed information for the currently active bin in a specific pool. Optimized endpoint for getting only the active bin data without loading all bins.
     */
    get: operations['get_active_bin_api_quotes_v1_bins__pool_id__active_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/v1/bins/{pool_id}/{bin_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Bin Detail
     * @description Get detailed information for a specific bin including reserves, price, liquidity, and active status. Useful for detailed pool analysis.
     */
    get: operations['get_bin_detail_api_quotes_v1_bins__pool_id___bin_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/v1/swap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate Swap Parameters
     * @description Convert quote execution path into swap parameters and post conditions for transaction execution. Takes quote data and returns contract call parameters.
     */
    post: operations['generate_swap_parameters_api_quotes_v1_swap_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/v1/users/{user_address}/positions/{pool_id}/bins': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get User Position Bins
     * @description Get user bin positions for a specific pool from Redis. Returns the same data shape as the BFF endpoint for easy comparison.
     */
    get: operations['get_user_position_bins_api_quotes_v1_users__user_address__positions__pool_id__bins_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/v1/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * API Root
     * @description Root endpoint with API information and available endpoints
     */
    get: operations['root_api_quotes_v1__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/internal/clear-graph-cache': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Clear Cache
     * @description Clear the graph cache to force rebuild on next request
     */
    post: operations['clear_cache_api_quotes_internal_clear_graph_cache_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/internal/performance': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Performance Metrics (Deprecated)
     * @deprecated
     * @description DEPRECATED: This endpoint is deprecated. Performance metrics are now available in Datadog. Use Datadog UI to view metrics. This endpoint returns minimal information for backward compatibility.
     */
    get: operations['get_performance_metrics_api_quotes_internal_performance_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/internal/performance/clear': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Clear Performance Metrics (Deprecated)
     * @deprecated
     * @description DEPRECATED: This endpoint is deprecated. Metrics are now in Datadog and cannot be cleared via API.
     */
    post: operations['clear_performance_metrics_api_quotes_internal_performance_clear_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/internal/token-graph': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Token Graph
     * @description Get the current token graph for analysis and troubleshooting.
     *
     *     Returns:
     *         Token graph data including nodes, edges, and pool information
     */
    get: operations['get_token_graph_api_quotes_internal_token_graph_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/internal/data/indexer-state': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Indexer State
     * @description Get current indexer state from PostgreSQL database including last processed block and health status for both DLMM and XYK indexers.
     */
    get: operations['get_indexer_state_api_quotes_internal_data_indexer_state_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/internal/data/indexer-lag': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Indexer lag vs Bitflow BFF chain tip
     * @description Compare indexer last_processed_block to BFF /api/stacks/extended chain_tip.block_height. Logs and emits indexer.lag.blocks metric when behind. Use for alerting and frequency analysis.
     */
    get: operations['get_indexer_lag_api_quotes_internal_data_indexer_lag_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/internal/data/block-processing-stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Block Processing Statistics
     * @description Get comprehensive block processing statistics including completion rates, event counts, and recent block data.
     */
    get: operations['get_block_processing_stats_api_quotes_internal_data_block_processing_stats_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/internal/data/processing-health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Processing Health Summary
     * @description Get processing health summary including recent failures, performance metrics, and processing lag information.
     */
    get: operations['get_processing_health_api_quotes_internal_data_processing_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/internal/data/database-info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Database Information
     * @description Get database information and statistics including size, table sizes, and connection information.
     */
    get: operations['get_database_info_api_quotes_internal_data_database_info_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description Check the health status of the service, Redis, and PostgreSQL connections. Returns detailed information about system status and connectivity.
     */
    get: operations['health_check_api_quotes_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Api Root
     * @description API root endpoint with version information
     */
    get: operations['api_root_api_quotes__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/favicon.ico': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Favicon
     * @description Favicon endpoint - returns 204 No Content to prevent 404 errors
     */
    get: operations['favicon_favicon_ico_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * BinData
     * @description Bin data model
     */
    BinData: {
      /**
       * Pool Id
       * @example dlmm_1
       */
      pool_id: string;
      /**
       * Bin Id
       * @example 500
       */
      bin_id: number;
      /**
       * Reserve X
       * @example 1000947397386
       */
      reserve_x: string;
      /**
       * Reserve Y
       * @example 10001078963244
       */
      reserve_y: string;
      /**
       * Price
       * @example 1000000000.0
       */
      price?: string | null;
      /**
       * Liquidity
       * @example 11002026360630
       */
      liquidity?: string | null;
    };
    /**
     * BinDetailResponse
     * @description Response for bin detail endpoint
     */
    BinDetailResponse: {
      /**
       * Success
       * @example true
       */
      success: boolean;
      /**
       * Pool Id
       * @example dlmm_1
       */
      pool_id: string;
      /**
       * Bin Id
       * @example 500
       */
      bin_id: number;
      /**
       * Reserve X
       * @example 1000947397386
       */
      reserve_x: string;
      /**
       * Reserve Y
       * @example 10001078963244
       */
      reserve_y: string;
      /**
       * Price
       * @example 1000000000.0
       */
      price?: string | null;
      /**
       * Liquidity
       * @example 11002026360630
       */
      liquidity?: string | null;
      /**
       * Is Active
       * @default false
       * @example true
       */
      is_active: boolean;
      /**
       * Error
       * @description Error message if request failed
       */
      error?: string | null;
    };
    /**
     * BinListResponse
     * @description Response for bin list endpoint
     */
    BinListResponse: {
      /**
       * Success
       * @example true
       */
      success: boolean;
      /**
       * Pool Id
       * @example dlmm_1
       */
      pool_id: string;
      /**
       * Bins
       * @description List of bin data
       */
      bins: components['schemas']['BinData'][];
      /**
       * Total Bins
       * @example 1001
       */
      total_bins: number;
      /**
       * Active Bin Id
       * @example 500
       */
      active_bin_id?: number | null;
      /**
       * Error
       * @description Error message if request failed
       */
      error?: string | null;
    };
    /**
     * BlockProcessingStatsResponse
     * @description Block processing statistics response model
     */
    BlockProcessingStatsResponse: {
      /**
       * Success
       * @description Whether the request was successful
       * @example true
       */
      success: boolean;
      /**
       * Stats
       * @description Block processing statistics
       */
      stats: {
        [key: string]: unknown;
      };
      /**
       * Error
       * @description Error message if request failed
       */
      error?: string | null;
    };
    /**
     * DatabaseInfoResponse
     * @description Database information response model
     */
    DatabaseInfoResponse: {
      /**
       * Success
       * @description Whether the request was successful
       * @example true
       */
      success: boolean;
      /**
       * Database Info
       * @description Database information and statistics
       */
      database_info: {
        [key: string]: unknown;
      };
      /**
       * Error
       * @description Error message if request failed
       */
      error?: string | null;
    };
    /**
     * ExecutionStep
     * @description Execution step for router contract
     */
    ExecutionStep: {
      /**
       * Pool Trait
       * @description Pool contract address/trait identifier
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.statutory-apricot-mule
       */
      pool_trait: string;
      /**
       * Pool Id
       * @description Pool ID for Redis lookup
       * @example dlmm_1
       */
      pool_id?: string | null;
      /**
       * X Token Trait
       * @description X token trait identifier
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.variable-copper-roundworm
       */
      x_token_trait: string;
      /**
       * Y Token Trait
       * @description Y token trait identifier
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.golden-aquamarine-trout
       */
      y_token_trait: string;
      /**
       * Expected Bin Id
       * @description Expected bin identifier
       * @example 500
       */
      expected_bin_id: number;
      /**
       * Function Name
       * @description Function name (swap-x-for-y or swap-y-for-x)
       * @example swap-x-for-y
       */
      function_name: string;
      /**
       * X In
       * @description X token input amount for this bin
       * @example 1000000
       */
      x_in?: string | null;
      /**
       * Y In
       * @description Y token input amount for this bin
       * @example 1000000
       */
      y_in?: string | null;
      /**
       * X Out
       * @description X token output amount from this bin
       * @example 9995000
       */
      x_out?: string | null;
      /**
       * Y Out
       * @description Y token output amount from this bin
       * @example 9995000
       */
      y_out?: string | null;
      /**
       * Is Empty Swap
       * @description Flag indicating this is an empty swap (amount=1, min_received=0) used to move active bin
       * @example false
       */
      is_empty_swap?: boolean | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HealthResponse
     * @description Health check response model
     */
    HealthResponse: {
      /**
       * Status
       * @description Service status
       * @example healthy
       */
      status: string;
      /**
       * Redis Connected
       * @description Redis connection status
       * @example true
       */
      redis_connected: boolean;
      /**
       * Redis Info
       * @description Redis connection information
       * @example {
       *       "connected": true,
       *       "connected_clients": 1,
       *       "environment": "local",
       *       "redis_version": "7.0.0",
       *       "used_memory_human": "2.1M"
       *     }
       */
      redis_info: {
        [key: string]: unknown;
      };
      /**
       * Version
       * @description API version
       * @example 1.0.0
       */
      version: string;
    };
    /**
     * IndexerLagEntry
     * @description Per-indexer lag vs Bitflow BFF chain tip
     */
    IndexerLagEntry: {
      /**
       * Last Processed Block
       * @description Last block processed by indexer
       */
      last_processed_block?: number | null;
      /**
       * Lag Blocks
       * @description Chain tip height minus last_processed_block
       */
      lag_blocks?: number | null;
      /**
       * Behind
       * @description True if lag_blocks is above threshold
       * @default false
       */
      behind: boolean;
    };
    /**
     * IndexerLagResponse
     * @description Indexer lag vs Bitflow BFF /stacks/extended chain tip. For alerting and frequency analysis.
     */
    IndexerLagResponse: {
      /**
       * Success
       * @description Whether the check succeeded
       */
      success: boolean;
      /**
       * Hiro Block Height
       * @description Canonical chain tip from Hiro extended (api.hiro.so). behind=true if Bitflow or indexer >threshold behind this.
       */
      hiro_block_height?: number | null;
      /**
       * Bitflow Block Height
       * @description Chain tip block height from BFF /api/stacks/extended
       */
      bitflow_block_height?: number | null;
      /** @description DLMM indexer lag (last_processed_block, lag_blocks, behind) */
      dlmm?: components['schemas']['IndexerLagEntry'] | null;
      /** @description XYK indexer lag (not supported; always null) */
      xyk?: components['schemas']['IndexerLagEntry'] | null;
      /**
       * Behind
       * @description True if DLMM indexer >threshold behind Bitflow, or Bitflow >threshold behind Hiro
       * @default false
       */
      behind: boolean;
      /**
       * Lag Threshold Blocks
       * @description Lag threshold used for behind flag
       * @default 10
       */
      lag_threshold_blocks: number;
      /**
       * Error
       * @description Error message if extended fetch or check failed
       */
      error?: string | null;
    };
    /**
     * IndexerStateResponse
     * @description Indexer state response model
     */
    IndexerStateResponse: {
      /**
       * Success
       * @description Whether the request was successful
       * @example true
       */
      success: boolean;
      /**
       * Dlmm State
       * @description DLMM indexer state information
       */
      dlmm_state?: {
        [key: string]: unknown;
      } | null;
      /**
       * Xyk State
       * @description XYK indexer state information
       */
      xyk_state?: {
        [key: string]: unknown;
      } | null;
      /**
       * Error
       * @description Error message if request failed
       */
      error?: string | null;
    };
    /**
     * MultiRouteQuoteResponse
     * @description Multi-route quote response model
     */
    MultiRouteQuoteResponse: {
      /**
       * Success
       * @description Whether the quote was successful
       * @example true
       */
      success: boolean;
      /**
       * Routes
       * @description List of routes sorted by best to worst
       */
      routes: components['schemas']['RouteInfo'][];
      /**
       * Best Route Index
       * @description Index of the best route (1-based)
       * @example 1
       */
      best_route_index?: number | null;
      /**
       * Error
       * @description Error message if quote failed
       */
      error?: string | null;
    };
    /**
     * PairInfo
     * @description Pair information model
     */
    PairInfo: {
      /**
       * Output Token
       * @description Output token contract address
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.golden-aquamarine-trout
       */
      output_token: string;
      /**
       * Output Token Symbol
       * @description Output token symbol
       * @example testB
       */
      output_token_symbol: string;
      /**
       * Output Token Name
       * @description Output token name
       * @example testB Token
       */
      output_token_name: string;
      /**
       * Output Token Decimals
       * @description Number of decimal places for output token
       * @example 8
       */
      output_token_decimals: number;
      /**
       * Output Token Image
       * @description Output token image URL
       * @example https://example.com/token-image.png
       */
      output_token_image: string;
      /**
       * Pools
       * @description List of pool contract addresses that support this pair
       * @example [
       *       "SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.dlmm-pool-contract",
       *       "SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.xyk-pool-contract"
       *     ]
       */
      pools: string[];
      /**
       * Pools Id
       * @description List of pool IDs that support this pair
       * @example [
       *       "dlmm_1",
       *       "xyk_2"
       *     ]
       */
      pools_id: string[];
      /**
       * Amm Types
       * @description List of AMM types available for this pair
       * @example [
       *       "dlmm"
       *     ]
       */
      amm_types: string[];
    };
    /**
     * PairsResponse
     * @description Pairs response model
     */
    PairsResponse: {
      /**
       * Input Token
       * @description Input token contract address
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.variable-copper-roundworm
       */
      input_token: string;
      /**
       * Input Token Symbol
       * @description Input token symbol
       * @example testA
       */
      input_token_symbol: string;
      /**
       * Input Token Name
       * @description Input token name
       * @example testA Token
       */
      input_token_name: string;
      /**
       * Input Token Decimals
       * @description Number of decimal places for input token
       * @example 8
       */
      input_token_decimals: number;
      /**
       * Input Token Image
       * @description Input token image URL
       * @example https://example.com/token-image.png
       */
      input_token_image: string;
      /**
       * Pairs
       * @description List of reachable output tokens
       */
      pairs: components['schemas']['PairInfo'][];
    };
    /**
     * PoolInfo
     * @description Pool information model
     */
    PoolInfo: {
      /**
       * Pool Id
       * @description Pool identifier
       * @example dlmm_1
       */
      pool_id: string;
      /**
       * Amm Type
       * @description AMM type (e.g., 'dlmm', 'xyk')
       * @example dlmm
       */
      amm_type: string;
      /**
       * Token X
       * @description Token X contract address
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.variable-copper-roundworm
       */
      token_x: string;
      /**
       * Token Y
       * @description Token Y contract address
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.golden-aquamarine-trout
       */
      token_y: string;
      /**
       * Bin Step
       * @description Bin step in basis points
       * @example 100
       */
      bin_step: number;
      /**
       * Active Bin
       * @description Currently active bin ID
       * @example 500
       */
      active_bin: number;
      /**
       * Active
       * @description Whether pool is active
       * @example true
       */
      active: boolean;
      /**
       * Pool Status
       * @description Pool status string
       * @example true
       */
      pool_status?: string | null;
      /**
       * X Protocol Fee
       * @description Protocol fee for X→Y swaps (basis points)
       * @example 2
       */
      x_protocol_fee: number;
      /**
       * X Provider Fee
       * @description Provider fee for X→Y swaps (basis points)
       * @example 3
       */
      x_provider_fee: number;
      /**
       * X Variable Fee
       * @description Variable fee for X→Y swaps (basis points)
       * @example 0
       */
      x_variable_fee: number;
      /**
       * Y Protocol Fee
       * @description Protocol fee for Y→X swaps (basis points)
       * @example 2
       */
      y_protocol_fee: number;
      /**
       * Y Provider Fee
       * @description Provider fee for Y→X swaps (basis points)
       * @example 3
       */
      y_provider_fee: number;
      /**
       * Y Variable Fee
       * @description Variable fee for Y→X swaps (basis points)
       * @example 0
       */
      y_variable_fee: number;
      /**
       * Types
       * @description Pool types/categories
       * @example [
       *       "STABLE",
       *       "LST"
       *     ]
       */
      types?: string[] | null;
      /**
       * Sbtc Incentives
       * @description Whether pool has sBTC incentives
       * @example true
       */
      sbtc_incentives?: boolean | null;
      /**
       * Suggested
       * @description Whether pool is suggested/recommended
       * @example false
       */
      suggested?: boolean | null;
      /**
       * Initial Price
       * @description Initial price
       * @example 1000000000
       */
      initial_price?: string | null;
      /**
       * Pool Name
       * @description Pool name
       * @example testA-testB-LP
       */
      pool_name?: string | null;
      /**
       * Pool Symbol
       * @description Pool symbol
       * @example testA-testB
       */
      pool_symbol?: string | null;
      /**
       * Pool Uri
       * @description Pool URI
       * @example tense-salmon-roundworm.com
       */
      pool_uri?: string | null;
      /**
       * Creation Height
       * @description Creation height
       * @example 914844
       */
      creation_height?: string | null;
      /**
       * Variable Fees Manager
       * @description Variable fees manager
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1
       */
      variable_fees_manager?: string | null;
      /**
       * Fee Address
       * @description Fee address
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.total-aquamarine-elephant
       */
      fee_address?: string | null;
      /**
       * Variable Fees Cooldown
       * @description Variable fees cooldown
       * @example 0
       */
      variable_fees_cooldown?: string | null;
      /**
       * Freeze Variable Fees Manager
       * @description Freeze variable fees manager
       * @example false
       */
      freeze_variable_fees_manager?: string | null;
      /**
       * Core Address
       * @description Core address
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.working-amaranth-clownfish
       */
      core_address?: string | null;
      /**
       * Pool Token
       * @description Pool token
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.experimental-maroon-silkworm
       */
      pool_token?: string | null;
      /**
       * Creator
       * @description Creator address
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1
       */
      creator?: string | null;
      /**
       * X Total Fee Bps
       * @description X total fee in basis points
       * @example 5
       */
      x_total_fee_bps?: string | null;
      /**
       * Y Total Fee Bps
       * @description Y total fee in basis points
       * @example 5
       */
      y_total_fee_bps?: string | null;
    };
    /**
     * PoolsResponse
     * @description Pools response model
     */
    PoolsResponse: {
      /**
       * Pools
       * @description List of available pools
       */
      pools: components['schemas']['PoolInfo'][];
    };
    /**
     * PostCondition
     * @description Post condition for swap execution
     */
    PostCondition: {
      /**
       * Amount
       * @description Amount in atomic units (uint format)
       * @example 1000000
       */
      amount: string;
      /**
       * Sender Address
       * @description Sender address (tx-sender or pool contract)
       * @example tx-sender
       */
      sender_address: string;
      /**
       * Condition Code
       * @description Condition type
       * @example less_than_or_equal_to
       */
      condition_code: string;
      /**
       * Token Contract
       * @description Token contract address
       * @example SM1793C4R5PZ4NS4VQ4WMP7SKKYVH8JZEWSZ9HCCR.token-usdc-v-1-1::usdc
       */
      token_contract: string;
      /**
       * Token Decimals
       * @description Token decimals
       * @example 6
       */
      token_decimals: number;
      /**
       * Token Asset Name
       * @description Token asset name/trait
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.variable-copper-roundworm
       */
      token_asset_name: string;
      /**
       * Post Condition Type
       * @description Post condition type based on sender and token type
       * @example standard_fungible
       */
      post_condition_type: string;
    };
    /**
     * ProcessingHealthResponse
     * @description Processing health summary response model
     */
    ProcessingHealthResponse: {
      /**
       * Success
       * @description Whether the request was successful
       * @example true
       */
      success: boolean;
      /**
       * Health Summary
       * @description Processing health summary
       */
      health_summary: {
        [key: string]: unknown;
      };
      /**
       * Error
       * @description Error message if request failed
       */
      error?: string | null;
    };
    /**
     * QuoteRequest
     * @description Quote request model for token swaps
     */
    QuoteRequest: {
      /**
       * Input Token
       * @description Input token contract address
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.variable-copper-roundworm
       */
      input_token: string;
      /**
       * Output Token
       * @description Output token contract address
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.golden-aquamarine-trout
       */
      output_token: string;
      /**
       * Amount In
       * @description Input amount as string (large integer in atomic units)
       * @example 1000000
       */
      amount_in: string;
      /**
       * Amm Strategy
       * @description AMM strategy: 'best', 'preferred', 'pure'
       * @default best
       * @example best
       */
      amm_strategy: string;
      /**
       * Preferred Amm
       * @description Preferred AMM type when using 'preferred' or 'pure' strategy
       * @example dlmm
       */
      preferred_amm?: string | null;
      /**
       * Slippage Tolerance
       * @description Slippage tolerance percentage (0-50)
       * @default 3
       * @example 3
       */
      slippage_tolerance: number | null;
    };
    /**
     * QuoteResponse
     * @description Quote response model with execution details
     */
    QuoteResponse: {
      /**
       * Success
       * @description Whether the quote was successful
       * @example true
       */
      success: boolean;
      /**
       * Amount Out
       * @description Output amount as string
       * @example 2995802098.950524737631184408
       */
      amount_out: string;
      /**
       * Min Amount Out
       * @description Minimum amount out with slippage protection
       * @example 2905928035.980008995500248675
       */
      min_amount_out: string;
      /**
       * Slippage Tolerance
       * @description Slippage tolerance percentage used in calculation
       * @example 3
       */
      slippage_tolerance: number;
      /**
       * Route Path
       * @description List of tokens in the route
       * @example [
       *       "SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.variable-copper-roundworm",
       *       "SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.golden-aquamarine-trout"
       *     ]
       */
      route_path: string[];
      /**
       * Execution Path
       * @description Flattened execution steps for router
       */
      execution_path: components['schemas']['ExecutionStep'][];
      /**
       * Fee
       * @description Total fee as string
       * @example 900.0000
       */
      fee: string;
      /**
       * Price Impact Bps
       * @description Price impact in basis points
       * @example 0
       */
      price_impact_bps: number;
      /**
       * Price Impact Tokens
       * @description Price impact in output token amount (negative means worse execution)
       * @example 0
       */
      price_impact_tokens: string;
      /**
       * Error
       * @description Error message if quote failed
       */
      error?: string | null;
      /**
       * Input Token Decimals
       * @description Number of decimals for input token
       * @example 8
       */
      input_token_decimals?: number | null;
      /**
       * Output Token Decimals
       * @description Number of decimals for output token
       * @example 8
       */
      output_token_decimals?: number | null;
      /**
       * Execution Details
       * @description Detailed execution information including strategy, bins traversed, and AMM type
       * @example {
       *       "amm_type": "dlmm",
       *       "bins_traversed": 15,
       *       "strategy": "multi_bin",
       *       "unique_bins_used": 15
       *     }
       */
      execution_details?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * RouteInfo
     * @description Route information model
     */
    RouteInfo: {
      /**
       * Route Index
       * @description Route index (1-based)
       * @example 1
       */
      route_index: number;
      /**
       * Amount Out
       * @description Output amount as string
       * @example 2995802098.950524737631184408
       */
      amount_out: string;
      /**
       * Min Amount Out
       * @description Minimum amount out with slippage protection
       * @example 2905928035.980008995500248675
       */
      min_amount_out: string;
      /**
       * Slippage Tolerance
       * @description Slippage tolerance percentage used in calculation
       * @example 3
       */
      slippage_tolerance: number;
      /**
       * Route Path
       * @description List of tokens in the route
       * @example [
       *       "SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.variable-copper-roundworm",
       *       "SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.golden-aquamarine-trout"
       *     ]
       */
      route_path: string[];
      /**
       * Execution Path
       * @description Flattened execution steps for router
       */
      execution_path: components['schemas']['ExecutionStep'][];
      /**
       * Fee
       * @description Total fee as string
       * @example 900.0000
       */
      fee: string;
      /**
       * Price Impact Bps
       * @description Price impact in basis points (aggregated across all hops)
       * @example 0
       */
      price_impact_bps: number;
      /**
       * Price Impact Tokens
       * @description Price impact in output token amount (aggregated across all hops, negative means worse execution)
       * @example 0
       */
      price_impact_tokens: string;
      /**
       * Total Hops
       * @description Number of hops in the route
       * @example 1
       */
      total_hops: number;
      /**
       * Input Token Decimals
       * @description Number of decimal places for input token
       * @example 8
       */
      input_token_decimals?: number | null;
      /**
       * Output Token Decimals
       * @description Number of decimal places for output token
       * @example 8
       */
      output_token_decimals?: number | null;
      /**
       * Execution Details
       * @description Detailed execution information including strategy, fees, and price impact
       */
      execution_details?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * SwapParameter
     * @description Individual swap parameter for a bin
     */
    SwapParameter: {
      /**
       * Pool Trait
       * @description Pool trait identifier
       * @example .dlmm-pool-sbtc-usdc-v-1-1
       */
      pool_trait: string;
      /**
       * X Token Trait
       * @description X token trait identifier
       * @example .token-sbtc
       */
      x_token_trait: string;
      /**
       * Y Token Trait
       * @description Y token trait identifier
       * @example .token-stx-v-1-1
       */
      y_token_trait: string;
      /**
       * Expected Bin Id
       * @description Expected bin ID for the swap
       * @example 500
       */
      expected_bin_id: number;
      /**
       * Amount
       * @description Amount to swap in atomic units
       * @example 100000000
       */
      amount: string;
      /**
       * Min Received
       * @description Minimum amount to receive (with slippage protection)
       * @example 95000000
       */
      min_received: string;
      /**
       * X For Y
       * @description True for X→Y swap, False for Y→X swap
       * @example true
       */
      x_for_y: boolean;
    };
    /**
     * SwapParameterTyped
     * @description Individual swap parameter with typed tuple structure for easier integration
     */
    SwapParameterTyped: {
      /**
       * Type
       * @description Parameter type
       * @example tuple
       */
      type: string;
      /**
       * Value
       * @description Tuple value containing all parameters. Can contain TypedParameterValue or nested SwapParameterTyped for nested tuples
       */
      value: {
        [key: string]: unknown;
      };
    };
    /**
     * SwapRequest
     * @description Request model for generating swap parameters and post conditions
     */
    SwapRequest: {
      /**
       * Execution Path
       * @description Execution path from quote response
       */
      execution_path: components['schemas']['ExecutionStep'][];
      /**
       * Amount In
       * @description Input amount in atomic units
       * @example 100000000
       */
      amount_in: string;
      /**
       * Amount Out
       * @description Expected output amount in atomic units
       * @example 998500000
       */
      amount_out: string;
      /**
       * Input Token
       * @description Input token contract address
       */
      input_token: string;
      /**
       * Output Token
       * @description Output token contract address
       */
      output_token: string;
      /**
       * Input Token Decimals
       * @description Input token decimals from quote response
       */
      input_token_decimals?: number | null;
      /**
       * Output Token Decimals
       * @description Output token decimals from quote response
       */
      output_token_decimals?: number | null;
      /**
       * Slippage Tolerance
       * @description Slippage tolerance percentage (0-50)
       * @default 3
       * @example 3
       */
      slippage_tolerance: number | null;
      /**
       * Provider
       * @description Optional aggregator fee provider principal address (for XYK swaps). If not provided, aggregator fees are not collected.
       * @example SP1234567890123456789012345678901234567890
       */
      provider?: string | null;
      /**
       * Swap Parameters Type
       * @description Type of swap parameters to generate: 'simple' (grouped by pool and direction) or 'full' (individual bin parameters). Defaults to 'simple'.
       * @default simple
       * @example simple
       */
      swap_parameters_type: string | null;
    };
    /**
     * SwapResponse
     * @description Response model for swap parameters and post conditions
     */
    SwapResponse: {
      /**
       * Success
       * @example true
       */
      success: boolean;
      /**
       * Slippage Tolerance
       * @description Slippage tolerance percentage used in calculation
       * @example 3
       */
      slippage_tolerance: number;
      /**
       * Swap Contract
       * @description Swap contract address
       * @example SM3FSH09DJJKRVRPF187Q628R3W4C91EQ3YST6PMV.dlmm-swap-router-v-0-1
       */
      swap_contract: string;
      /**
       * Function Name
       * @description Function name to call
       * @example swap-multi
       */
      function_name: string;
      /**
       * Swap Parameters
       * @description List of swap parameters (full or simple grouped)
       */
      swap_parameters: (
        | components['schemas']['SwapParameter']
        | components['schemas']['SwapSimpleParameter']
      )[];
      /**
       * Swap Parameters Typed
       * @description List of typed swap parameters (full or simple grouped)
       */
      swap_parameters_typed: (
        | components['schemas']['SwapParameterTyped']
        | components['schemas']['SwapSimpleParameterTyped']
      )[];
      /**
       * Post Conditions
       * @description Post conditions for swap execution
       */
      post_conditions: components['schemas']['PostCondition'][];
      /**
       * Total Hops
       * @description Number of pools/hops
       * @example 1
       */
      total_hops: number;
      /**
       * Error
       * @description Error message if request failed
       */
      error?: string | null;
    };
    /**
     * SwapSimpleParameter
     * @description Simple swap parameter for grouped bins (swap-simple-multi)
     */
    SwapSimpleParameter: {
      /**
       * Pool Trait
       * @description Pool trait identifier
       * @example .dlmm-pool-sbtc-usdc-v-1-1
       */
      pool_trait: string;
      /**
       * X Token Trait
       * @description X token trait identifier
       * @example .token-sbtc
       */
      x_token_trait: string;
      /**
       * Y Token Trait
       * @description Y token trait identifier
       * @example .token-stx-v-1-1
       */
      y_token_trait: string;
      /**
       * Amount
       * @description Total amount to swap in atomic units (sum of all bins in group)
       * @example 100000000
       */
      amount: string;
      /**
       * Min Received
       * @description Total minimum amount to receive (sum of all bins in group, with slippage protection)
       * @example 95000000
       */
      min_received: string;
      /**
       * X For Y
       * @description True for X→Y swap, False for Y→X swap
       * @example true
       */
      x_for_y: boolean;
      /**
       * Max Steps
       * @description Maximum number of bins to traverse in this group
       * @example 7
       */
      max_steps: number;
    };
    /**
     * SwapSimpleParameterTyped
     * @description Simple swap parameter with typed tuple structure for swap-simple-multi
     */
    SwapSimpleParameterTyped: {
      /**
       * Type
       * @description Parameter type
       * @example tuple
       */
      type: string;
      /**
       * Value
       * @description Tuple value containing all simple swap parameters. Can contain TypedParameterValue
       */
      value: {
        [key: string]: unknown;
      };
    };
    /**
     * TokenInfo
     * @description Token information model
     */
    TokenInfo: {
      /**
       * Contract Address
       * @description Token contract address
       * @example SP1WA4CXFR54B1W42R7NSMXEQYQTTMB3CXQ3FVJE1.variable-copper-roundworm
       */
      contract_address: string;
      /**
       * Symbol
       * @description Token symbol
       * @example testA
       */
      symbol: string;
      /**
       * Name
       * @description Token name
       * @example testA Token
       */
      name: string;
      /**
       * Decimals
       * @description Number of decimal places
       * @example 8
       */
      decimals: number;
      /**
       * Asset Name
       * @description Token asset name/trait
       * @example variable-copper-roundworm
       */
      asset_name: string;
      /**
       * Total Supply
       * @description Total token supply
       * @example 1000000000
       */
      total_supply?: number | null;
      /**
       * Image
       * @description Token image URL
       * @example https://example.com/token.png
       */
      image?: string | null;
    };
    /**
     * TokensResponse
     * @description Tokens response model
     */
    TokensResponse: {
      /**
       * Tokens
       * @description List of supported tokens
       */
      tokens: components['schemas']['TokenInfo'][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_quote_api_quotes_v1_quote_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['QuoteRequest'];
      };
    };
    responses: {
      /** @description Quote response with execution path and details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuoteResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_multi_route_quote_api_quotes_v1_quote_multi_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['QuoteRequest'];
      };
    };
    responses: {
      /** @description Multiple routes sorted by output amount */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MultiRouteQuoteResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_tokens_api_quotes_v1_tokens_get: {
    parameters: {
      query?: {
        /** @description Filter by AMM type (e.g., 'dlmm', 'xyk') */
        amm_type?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokensResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_pools_api_quotes_v1_pools_get: {
    parameters: {
      query?: {
        /** @description Filter by AMM type (e.g., 'dlmm', 'xyk') */
        amm_type?: string | null;
        /** @description Filter by suggested pools */
        suggested?: boolean | null;
        /** @description Filter by sBTC incentives */
        sbtc_incentives?: boolean | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PoolsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_pool_by_id_api_quotes_v1_pools__pool_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pool_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Pool information */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PoolInfo'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_pairs_api_quotes_v1_pairs_get: {
    parameters: {
      query: {
        input_token: string;
        output_token?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of available output tokens and their pools */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PairsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_pool_bins_api_quotes_v1_bins__pool_id__get: {
    parameters: {
      query?: never;
      header?: {
        /** @description Enable on-chain data fallback when DB data is stale (default: Redis only) */
        'X-Allow-Fallback'?: boolean;
      };
      path: {
        pool_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all bins in the pool with detailed information */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BinListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_active_bin_api_quotes_v1_bins__pool_id__active_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pool_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active bin information */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BinDetailResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_bin_detail_api_quotes_v1_bins__pool_id___bin_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pool_id: string;
        bin_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Detailed bin information */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BinDetailResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  generate_swap_parameters_api_quotes_v1_swap_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SwapRequest'];
      };
    };
    responses: {
      /** @description Swap parameters and post conditions for transaction execution */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SwapResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_user_position_bins_api_quotes_v1_users__user_address__positions__pool_id__bins_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_address: string;
        pool_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User bin positions with bin_id, price, and userLiquidity */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  root_api_quotes_v1__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API information and endpoint list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  clear_cache_api_quotes_internal_clear_graph_cache_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_performance_metrics_api_quotes_internal_performance_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deprecated performance metrics response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  clear_performance_metrics_api_quotes_internal_performance_clear_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_token_graph_api_quotes_internal_token_graph_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_indexer_state_api_quotes_internal_data_indexer_state_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Indexer state information for DLMM and XYK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IndexerStateResponse'];
        };
      };
    };
  };
  get_indexer_lag_api_quotes_internal_data_indexer_lag_get: {
    parameters: {
      query?: {
        /** @description When 'testnet', use Hiro testnet for canonical chain tip (for validation against testnet). */
        network?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Indexer lag vs Bitflow BFF chain tip */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IndexerLagResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_block_processing_stats_api_quotes_internal_data_block_processing_stats_get: {
    parameters: {
      query?: {
        /** @description Maximum number of recent blocks to analyze */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Block processing statistics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BlockProcessingStatsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_processing_health_api_quotes_internal_data_processing_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Processing health summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProcessingHealthResponse'];
        };
      };
    };
  };
  get_database_info_api_quotes_internal_data_database_info_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Database information and statistics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DatabaseInfoResponse'];
        };
      };
    };
  };
  health_check_api_quotes_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Health status and connection information */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  api_root_api_quotes__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  favicon_favicon_ico_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
