export enum AllBalancesSelectors {
  AllBalancesMenuItem = 'settings-all-balances',
  AllBalancesPage = 'all-balances-page',
  AllBalancesDetailPage = 'all-balances-detail-page',
  TotalBalance = 'all-balances-total',
  BitcoinProtocolSection = 'bitcoin-protocol-section',
  StacksProtocolSection = 'stacks-protocol-section',
  BalanceRowAvailable = 'balance-row-available',
  BalanceRowPending = 'balance-row-pending',
  BalanceRowSending = 'balance-row-sending',
  BalanceRowUneconomical = 'balance-row-uneconomical',
  BalanceRowStxAvailable = 'balance-row-stx-available',
  BalanceRowStxLocked = 'balance-row-stx-locked',
  BalanceRowStxPending = 'balance-row-stx-pending',
  BalanceRowSip10 = 'balance-row-sip10',
  BalanceRowSbtc = 'balance-row-sbtc',
  DetailTotal = 'all-balances-detail-total',
  DetailAddressGroup = 'all-balances-detail-address-group',
  DetailUtxoRow = 'all-balances-detail-utxo-row',
  DetailEmpty = 'all-balances-detail-empty',
}
