export enum CollectibleDetailsSelectors {
  CollectibleDetailsContainer = 'collectible-details-container',
  CollectibleDetailsBack = 'collectible-details-back',
  CollectibleDetailsSend = 'collectible-details-send',
  CollectibleDetailsOptions = 'collectible-details-options',
  CollectibleDetailsTitle = 'collectible-details-title',
  CollectibleDetailsSubtitle = 'collectible-details-subtitle',
  CollectibleDetailsMedia = 'collectible-details-media',
  CollectibleCard = 'collectible-card',
  CollectibleCardInscription = 'collectible-card-inscription',
  CollectibleCardSip9 = 'collectible-card-sip9',
  CollectibleCardStamp = 'collectible-card-stamp',
  ViewOriginalMenuItem = 'view-original-menu-item',
  ProtectMenuItem = 'protect-menu-item',
  UnprotectMenuItem = 'unprotect-menu-item',
  InscriptionDetailsSection = 'inscription-details-section',
  InscriptionOutputValue = 'inscription-output-value',
  Sip9DetailsSection = 'sip9-details-section',
  Sip9FloorPrice = 'sip9-floor-price',
  Sip9LastSale = 'sip9-last-sale',
  Sip9Description = 'sip9-description',
  Sip9Attributes = 'sip9-attributes',
  StampDetailsSection = 'stamp-details-section',
}
