export enum HomePageSelectors {
  AssetList = 'asset-list',
  AvailableBalance = 'available-balance',
  HomePageContainer = 'home-page-container',
  ReceiveCryptoAssetBtn = 'receive-crypto-asset-btn',
  ReceiveBtcNativeSegwitQrCodeBtn = 'receive-native-segwit-qr-code-btn',
  ReceiveAssetsTab = 'receive-assets-tab',
  ReceiveCollectiblesTab = 'receive-collectibles-tab',
  ReceiveStxQrCodeBtn = 'receive-stx-qr-code-btn',
  SendCryptoAssetBtn = 'send-crypto-asset-btn',
  TokensTabBtn = 'tab-tokens',
  CollectiblesTabBtn = 'tab-collectibles',
  ActivityTabBtn = 'tab-activity',
  SwapBtn = 'swap-btn',
  FundAccountBtn = 'fund-account-btn',
  SellBtn = 'sell-btn',
  ManageTokensBtn = 'manage-tokens-btn',
  ManageTokensAssetsList = 'manage-tokens-assets-list',
  NetworkSwitcher = 'network-switcher',
  TrendingToken = 'trending-token-',
}
