export enum TokenDetailsSelectors {
  TokenDetailsContainer = 'token-details-container',
  TokenDetailsBackButton = 'token-details-back',
  TokenDetailsTitle = 'token-details-title',
  TokenDetailsLoading = 'token-details-loading',
  TokenDetailsError = 'token-details-error',
  TokenOverview = 'token-overview',
  TokenOverviewAmount = 'token-overview-amount',
  TokenOverviewFiatAmount = 'token-overview-fiat-amount',
  TokenDetailsSendButton = 'token-details-send-btn',
  TokenDetailsReceiveButton = 'token-details-receive-btn',
  TokenDetailsBuyButton = 'token-details-buy-btn',
  TokenDetailsSwapButton = 'token-details-swap-btn',
  TokenDetailsDescription = 'token-details-description',
  TokenDetailsName = 'token-details-name',
  TokenDetailsPrice = 'token-details-price',
  TokenDetailsPriceChange = 'token-details-price-change',
  TokenDetailsLayer = 'token-details-layer',
  TokenDetailsBalancesSection = 'token-details-balances',
  TokenDetailsActivitySection = 'token-details-activity',
  TokenDetailsLockedRow = 'token-details-locked-row',
  TokenDetailsBalanceAvailable = 'token-details-balance-available',
  TokenDetailsActivityEmpty = 'token-details-activity-empty',
  TokenDetailsActivityLoading = 'token-details-activity-loading',
  TokenDetailsTabActivity = 'token-details-tab-activity',
  TokenDetailsTabBalances = 'token-details-tab-balances',
  TokenDetailsTabInfo = 'token-details-tab-info',
}
