import { z } from 'zod';

const bestInSlotInscriptionDelegateSchema = z.object({
  delegate_id: z.string(),
  render_url: z.string().nullable().optional(),
  mime_type: z.string().nullable().optional(),
  content_url: z.string(),
  bis_url: z.string(),
});

export const bestInSlotInscriptionSchema = z.object({
  inscription_name: z.string().nullable().optional(),
  inscription_id: z.string(),
  inscription_number: z.number(),
  parent_ids: z.array(z.string()),
  metadata: z.any().nullable(),
  owner_wallet_addr: z.string(),
  mime_type: z.string().nullable().optional(),
  last_sale_price: z.number().nullable().optional(),
  slug: z.string().nullable().optional(),
  collection_name: z.string().nullable().optional(),
  satpoint: z.string(),
  last_transfer_block_height: z.number().nullable().optional(),
  genesis_height: z.number(),
  content_url: z.string(),
  bis_url: z.string(),
  render_url: z.string().nullable().optional(),
  bitmap_number: z.number().nullable().optional(),
  delegate: bestInSlotInscriptionDelegateSchema.nullable().optional(),
  output_value: z.number(),
  genesis_ts: z.string(),
  genesis_block_hash: z.string(),
});

export const inscriptionsByAddressSchema = z.object({
  block_height: z.number(),
  data: z.array(bestInSlotInscriptionSchema),
});

export const bestInslotInscriptionBatchInfoSchema = z.object({
  inscription_name: z.string().nullable().optional(),
  inscription_id: z.string(),
  inscription_number: z.number(),
  parent_ids: z.array(z.string()),
  metadata: z.any().nullable(),
  wallet: z.string(),
  mime_type: z.string().nullable().optional(),
  media_length: z.number().nullable().optional(),
  byte_size: z.union([z.number(), z.object({})]),
  genesis_ts: z.number(),
  genesis_height: z.number(),
  genesis_fee: z.number().nullable().optional(),
  output_value: z.number().nullable().optional(),
  satpoint: z.string(),
  last_sale_price: z.number().nullable().optional(),
  collection_name: z.string().nullable().optional(),
  collection_slug: z.string().nullable().optional(),
  last_transfer_block_height: z.number().nullable().optional(),
  utxo: z.string(),
  collection_floor_price: z.number().nullable().optional(),
  min_price: z.number().nullable().optional(),
  ordswap_price: z.number().nullable().optional(),
  magiceden_price: z.number().nullable().optional(),
  ordinalswallet_price: z.number().nullable().optional(),
  gammaio_price: z.number().nullable().optional(),
  nostr_price: z.number().nullable().optional(),
  odynals_price: z.number().nullable().optional(),
  unisat_price: z.number().nullable().optional(),
  ordinalsmarket_price: z.number().nullable().optional(),
  okx_price: z.number().nullable().optional(),
  content_url: z.string(),
  bis_url: z.string(),
  render_url: z.string().nullable().optional(),
  bitmap_number: z.number().nullable().optional(),
  delegate: bestInSlotInscriptionDelegateSchema.nullable().optional(),
});
