/* do not change this file, it is auto generated by storybook. */
import { start } from '@storybook/react-native';

const normalizedStories = [
  {
    titlePrefix: 'UI',
    directory: './components',
    files: '**/*.native.stories.?(ts|tsx|js|jsx)',
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.native.stories\.(?:ts|tsx|js|jsx)?)$/,
    req: require.context(
      '../components',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.native.stories\.(?:ts|tsx|js|jsx)?)$/
    ),
  },
];

// @ts-expect-error: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.
global.STORIES = normalizedStories;

export const view = start({
  annotations: [require('./preview')],
  storyEntries: normalizedStories,
});
