platform :ios do
  desc "Build and distribute iOS app"
  lane :distribute_ios do
    build_app(
      scheme: "leatherwalletmobile"
    )
    firebase_app_distribution(
      app: "1:915379517791:ios:ecfa47ab5ee5f256789eea",
      groups: "leatherhood",
      release_notes: "New build available"
    )
  end

    lane :build do
      match(type: "development", readonly: true)
    gym(
      workspace: "YourApp.xcworkspace",
      scheme: "leatherwalletmobile",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "io.leather.mobilewallet" => "leatherhood"
        }
      },
      xcargs: "-allowProvisioningUpdates"
    )
  end
end

