platform :ios do
  desc "Build and distribute iOS app"
  lane :distribute_ios do
    build_app(
      scheme: "leatherwalletmobile"
    )
    firebase_app_distribution(
      app: "1:915379517791:ios:ecfa47ab5ee5f256789eea",
      groups: "leatherhood",
      release_notes: "New build available"
    )
  end
end

