export const WaitlistIds = {
  fees: 'fees',
  bitgo: 'bitgo',
  capsule: 'capsule',
  copper: 'copper',
  fireblocks: 'fireblocks',
  foredefi: 'foredefi',
  portal: 'portal',
  privy: 'privy',
  qredo: 'qredo',
  addressReuse: 'addressReuse',
  addressScanRange: 'addressScanRange',
  addressTypes: 'addressTypes',
  exportXpub: 'exportXpub',
  exportKey: 'exportKey',
  contacts: 'contacts',
  restoreViaEmail: 'restoreViaEmail',
  watchOnlyWallet: 'watchOnlyWallet',
  bitkey: 'bitkey',
};
