name: Build Leather Android
description: Build the Leather Mobile Android App
inputs:
  EXPO_TOKEN:
    description: 'Expo token for authentication'
    required: true
  GOOGLE_SERVICES_JSON:
    description: 'Google Services JSON file'
    required: true

outputs:
  aab_path:
    description: 'Path to the built AAB file'
    value: ${{ steps.set-aab-path.outputs.aab_path }}

runs:
  using: 'composite'
  steps:
    - name: Provision
      uses: ./.github/actions/provision

    - name: Build local dependencies
      run: pnpm turbo run build --force --no-cache
      shell: bash

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ inputs.EXPO_TOKEN }}

    - name: Decode GOOGLE_SERVICES_JSON
      shell: bash
      working-directory: ./apps/mobile
      run: |
        echo $GOOGLE_SERVICES_JSON > ./android/app/google-services.json
        ls -l ./android/app/google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ inputs.GOOGLE_SERVICES_JSON }}

    - name: Build Android app
      shell: bash
      working-directory: ./apps/mobile
      run: |
        eas build --local \
        --platform android \
        --profile production \
        --non-interactive \
        --output ${{ github.workspace }}/app-release.aab
      env:
        NODE_ENV: production

    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release.aab
        path: ${{ github.workspace }}/app-release.aab

    - name: Set AAB path
      run: |
        echo "aab_path=${{ github.workspace }}/app-release.aab" >> $GITHUB_OUTPUT
      shell: bash
