import { BestInSlotInscriptionResponse } from '../src/bitcoin/clients/best-in-slot';
export declare const mockInscriptionResponse: BestInSlotInscriptionResponse;
export declare const mockInscription1: import("@leather.io/models").Inscription;
export declare const mockInscriptionResponse2: BestInSlotInscriptionResponse;
export declare const mockInscription2: import("@leather.io/models").Inscription;
export declare const mockInscriptionResponse3: {
    inscription_name: null;
    inscription_id: string;
    inscription_number: number;
    parent_ids: never[];
    output_value: number;
    genesis_block_hash: string;
    genesis_ts: string;
    metadata: null;
    owner_wallet_addr: string;
    mime_type: string;
    last_sale_price: null;
    slug: null;
    collection_name: null;
    satpoint: string;
    last_transfer_block_height: number;
    genesis_height: number;
    content_url: string;
    bis_url: string;
    render_url: null;
    bitmap_number: null;
    delegate: null;
};
export declare const mockInscriptionResponseNonZeroOffset: BestInSlotInscriptionResponse;
export declare const mockInscriptionResponsesList: {
    inscription_name: null;
    inscription_id: string;
    inscription_number: number;
    parent_ids: never[];
    output_value: number;
    genesis_block_hash: string;
    genesis_ts: string;
    metadata: null;
    owner_wallet_addr: string;
    mime_type: string;
    last_sale_price: null;
    slug: null;
    collection_name: null;
    satpoint: string;
    last_transfer_block_height: number;
    genesis_height: number;
    content_url: string;
    bis_url: string;
    render_url: null;
    bitmap_number: null;
    delegate: null;
}[];
export declare const mockInscriptionsList: import("@leather.io/models").Inscription[];
//# sourceMappingURL=mock-inscriptions.d.ts.map