name: Build
on:
  push:
    branches:
      - '**'
      - '!dev'

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Build iOS app
        id: buildiOS
        run: node apps/mobile-wallet/scripts/buildIos.js && echo "buildPath=$(xargs < iosBuildPath)" >> $GITHUB_OUTPUT

      - name: Upload iOS build to GitHub Actions Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mobilewallet.app
          path: ${{steps.buildiOS.outputs.buildPath}}
          if-no-files-found: error
  
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Build Android apk
        id: buildAndroid
        run: node apps/mobile-wallet/scripts/buildAndroid.js

      - name: Upload Android apk to GitHub Actions Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: apps/mobile-wallet/android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error

  bundle-ios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Bundle javascript for iOS
        run: cd ./apps/mobile-wallet && npx expo export --platform ios

  bundle-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Bundle javascript for Android
        run: cd ./apps/mobile-wallet && npx expo export --platform android