name: Check Fingerprint
on: pull_request_target
permissions:
  contents: read
  pull-requests: write
jobs:
  check-fingerprint:
    name: Check Fingerprint
    runs-on: ubuntu-latest
    steps:
      - name: Prepare the app
        uses: ./.github/actions/provision

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ inputs.EXPO_TOKEN }}

      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq
        shell: bash

      - name: Setup eas credentials
        run: |
          echo $(jq --arg APPLE_ID "$APPLE_ID" '.submit.production.ios.appleId = $APPLE_ID' ./apps/mobile/eas.json) > ./apps/mobile/eas.json
          echo $(jq --arg ASC_APP_ID "$ASC_APP_ID" '.submit.production.ios.ascAppId = $ASC_APP_ID' ./apps/mobile/eas.json) > ./apps/mobile/eas.json
        shell: bash
        env:
          APPLE_ID: ${{ inputs.APPLE_ID }}
          ASC_APP_ID: ${{ inputs.ASC_APP_ID }}

      # Wait for build to either succeed or fail
      - name: 🛫 Build for iOS Simulator 🛫
        id: simulator_build
        run: |
          eas fingerprint:generate -p ios --json --non-interactive | jq '.hash' | echo
        shell: bash
        env:
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ inputs.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}
          IS_MAIN_BRANCH: ${{ inputs.IS_MAIN_BRANCH }}

      - name: Publish simulator expo link in PR
        if: ${{ inputs.IS_MAIN_BRANCH == 'false' }}
        uses: actions/github-script@v7
        env:
          BUILD_LINK: ${{ steps.simulator_build.outputs.BUILD_LINK }}
        with:
          github-token: ${{ inputs.LEATHER_BOT }}
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const tag = "<!-- LEATHER_FINGERPRINT_TESTER --> \n\n\n"

            // Find existing comment by the bot
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('<!-- LEATHER_FINGERPRINT_TESTER -->')
            );
            const basicConfig = true ? {
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: tag + "This PR has a different fingerprint. Merging this PR would render"
            } : {
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: tag + "This PR has the same fingerprint. Merging this PR would not require us to submit a native build"
            }
            if(botComment) {
              github.rest.issues.updateComment({
                comment_id: botComment.id,
                ...basicConfig,
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                ...basicConfig
              })
            }

      - name: 🛫 Build for production 🛫
        if: ${{ inputs.IS_MAIN_BRANCH == 'true' }}
        run: |
          cd apps/mobile
          # Release version of the app, we should wait for it to see the result
          eas build --platform ios --profile=production --non-interactive --auto-submit
        shell: bash
        env:
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ inputs.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_ID: ${{ inputs.APPLE_ID }}
