name: Check Fingerprint
on: pull_request_target
permissions:
  contents: read
  pull-requests: write
jobs:
  check-fingerprint:
    name: Check Fingerprint
    runs-on: ubuntu-latest
    steps:
      - name: Prepare the app
        uses: ./.github/actions/provision

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ inputs.EXPO_TOKEN }}

      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq
        shell: bash
