name: Check PR linear merge

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  enforce-ff-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Set PR branch environment variable
        run: echo "PR_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Check for Fast-Forward Merge
        id: ff_check
        run: |
          git merge --ff-only origin/${{ env.PR_BRANCH }} || 
          (echo "Merge is not fast-forwardable. Failing workflow!"; exit 1)

      - name: Success Message
        if: success()
        run: echo "✅ Fast-Forward Merge is possible! The PR can be merged cleanly."
