name: Check signed commits

on:
  pull_request:
    branches-ignore: release-please*

permissions:
  contents: read
  pull-requests: write

jobs:
  check-signed-commits:
    name: Check signed commits
    if: github.event.head_commit.author.email != '163018147+leather-bot@users.noreply.github.com'
    runs-on: ubuntu-latest
    steps:
      - name: Check signed commits
        uses: 1Password/check-signed-commits-action@v1
