name: Check Fingerprint
on: pull_request_target
permissions:
  contents: read
  pull-requests: write
jobs:
  check-fingerprint:
    name: Check Fingerprint
    runs-on: ubuntu-latest
    steps:
      - name: Prepare the app
        uses: ./.github/actions/provision
