# FIXME ENG-14 - I can't see this running anywhere
# the translations are not updating anyway
# when we add a new key it creates a new empty translation in the crowdin dashboard
name: Crowdin Action

on:
  push:
    branches:
      - fix/crowdin-action

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Provision
        uses: ./.github/actions/provision

      - name: Extract lingui strings
        working-directory: ./apps/mobile
        run: |
          pnpm lingui

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          # Sync `en` translations with Crowdin
          upload_sources: true
          upload_language: 'en'
          upload_translations: true
          download_translations: true
          create_pull_request: true
          config: apps/mobile/crowdin.yml

        env:
          # A classic GitHub Personal Access Token with the 'repo' scope selected (the user should have write access to the repository).
          GITHUB_TOKEN: ${{ secrets.LEATHER_BOT }}

          # A numeric ID, found at https://crowdin.com/project/<projectName>/tools/api
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}

          # Visit https://crowdin.com/settings#api-key to create this token
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
