name: Deploy

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: ${{ github.ref == 'refs/heads/main' && 'web:production' || github.ref == 'refs/heads/dev' && 'web:staging' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: Build web app
        env:
          CLOUDFLARE_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/dev' && 'staging' }}
          LEATHER_TARGET: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/dev' && 'staging' }}
          LEATHER_SENTRY_DSN: ${{ secrets.LEATHER_WEB_SENTRY_DSN }}
          LEATHER_SENTRY_AUTH_TOKEN: ${{ secrets.LEATHER_SENTRY_AUTH_TOKEN }}
          LEATHER_SEGMENT_WRITE_KEY: ${{ vars.SEGMENT_WRITE_KEY }}
        run: pnpm turbo run build --filter="@leather.io/web"

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        env:
          CLOUDFLARE_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/dev' && 'staging' }}
        with:
          environment:
          workingDirectory: apps/web
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_LEATHER_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.LEATHER_BOT }}
