name: Trigger EAS deploy for iOS and Android
on:
  pull_request:
    types:
      - synchronize
      - labeled
permissions:
  contents: write
  pull-requests: write
jobs:
  deploy-eas-ios:
    if: contains(github.event.pull_request.labels.*.name, 'needs:demo-build')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/eas-deploy-ios
        with:
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          ASC_APP_ID: ${{ secrets.ASC_APP_ID }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          LEATHER_BOT: ${{ secrets.LEATHER_BOT }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  deploy-eas-android:
    if: contains(github.event.pull_request.labels.*.name, 'needs:demo-build')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/eas-deploy-android
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          LEATHER_BOT: ${{ secrets.LEATHER_BOT }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  distribute-ios-fastlane:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Node.js dependencies
        working-directory: ./apps/mobile
        run: pnpm install

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        working-directory: ./apps/mobile/ios
        run: bundle install

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        working-directory: ./apps/mobile/ios
        run: pod install

      - name: Run Fastlane
        working-directory: ./apps/mobile/ios
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: bundle exec fastlane ios distribute_ios
  distribute-android-fastlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Node.js dependencies
        working-directory: ./apps/mobile
        run: pnpm install

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        working-directory: ./apps/mobile/android
        run: bundle install

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Fastlane
        working-directory: ./apps/mobile/android
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64
        run: bundle exec fastlane android distribute_android
