name: extension:code-checks

on:
  merge_group:
  push:
    branches:
      - '**'
    paths:
      - 'apps/extension/**'
      - 'packages/**'
      - '!packages/ui/**/*.native.ts'
      - '!packages/ui/**/*.native.tsx'

# GITHUB_TOKEN only needs to read the repository for checkout.
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-unused-exports:
    name: lint-unused-exports
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/provision

      - name: lint-unused-typescript-exports
        working-directory: apps/extension
        run: pnpm lint:unused-exports

  lint-firefox-build:
    name: lint-firefox-build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/provision

      - run: pnpm build:packages

      - run: pnpm build
        working-directory: apps/extension
        env:
          TARGET_BROWSER: firefox

      - name: lint-firefox-build
        run: pnpm web-ext lint
        working-directory: apps/extension
