name: extension:development-build

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read

env:
  # NO SENTRY CURRENTLY
  SEGMENT_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_KEY_STAGING }}
  LAUNCH_DARKLY_KEY: ${{ secrets.EXTENSION_LAUNCH_DARKLY_KEY}}
  BITFLOW_API_HOST: ${{ secrets.BITFLOW_API_HOST }}
  BITFLOW_API_KEY: ${{ secrets.BITFLOW_API_KEY }}
  BITFLOW_READONLY_CALL_API_HOST: ${{ secrets.BITFLOW_READONLY_CALL_API_HOST }}
  BITFLOW_READONLY_CALL_API_KEY: ${{ secrets.BITFLOW_READONLY_CALL_API_KEY }}
  BITFLOW_KEEPER_API_KEY: ${{ secrets.BITFLOW_KEEPER_API_KEY }}
  BITFLOW_KEEPER_API_HOST: ${{ secrets.BITFLOW_KEEPER_API_HOST }}
  BITFLOW_PROVIDER_ADDRESS: ${{ secrets.BITFLOW_PROVIDER_ADDRESS }}
  PREVIEW_RELEASE: true
  WALLET_ENVIRONMENT: preview
  ONRAMPER_API_KEY: ${{ secrets.ONRAMPER_API_KEY }}
  ONRAMPER_WIDGET_HOST: ${{ secrets.ONRAMPER_WIDGET_HOST }}
  ONRAMPER_SIGNING_SECRET: ${{ secrets.ONRAMPER_SIGNING_SECRET }}

jobs:
  build-extension:
    runs-on: ubuntu-24.04
    outputs:
      new_version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: build-project
        env:
          IS_PUBLISHING: true
        run: pnpm build:extension

      - name: extract-version
        id: extract_version
        working-directory: apps/extension
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        name: Upload build artifact
        with:
          name: leather-io
          path: apps/extension/dist
