name: extension:publish-extensions

on: workflow_dispatch

permissions:
  contents: write
  actions: write

env:
  SENTRY_DSN: ${{ secrets.EXTENSION_SENTRY_DSN }}
  SEGMENT_WRITE_KEY: ${{ secrets.EXTENSION_SEGMENT_WRITE_KEY }}
  LAUNCH_DARKLY_KEY: ${{ secrets.EXTENSION_LAUNCH_DARKLY_KEY}}
  BITFLOW_API_HOST: ${{ secrets.BITFLOW_API_HOST }}
  BITFLOW_API_KEY: ${{ secrets.BITFLOW_API_KEY }}
  BITFLOW_READONLY_CALL_API_HOST: ${{ secrets.BITFLOW_READONLY_CALL_API_HOST }}
  BITFLOW_READONLY_CALL_API_KEY: ${{ secrets.BITFLOW_READONLY_CALL_API_KEY }}
  BITFLOW_KEEPER_API_KEY: ${{ secrets.BITFLOW_KEEPER_API_KEY }}
  BITFLOW_KEEPER_API_HOST: ${{ secrets.BITFLOW_KEEPER_API_HOST }}
  BITFLOW_PROVIDER_ADDRESS: ${{ secrets.BITFLOW_PROVIDER_ADDRESS }}
  WALLET_ENVIRONMENT: production
  IS_PUBLISHING: true
  ONRAMPER_API_KEY: ${{ secrets.ONRAMPER_API_KEY }}
  ONRAMPER_WIDGET_HOST: ${{ secrets.ONRAMPER_WIDGET_HOST }}
  ONRAMPER_SIGNING_SECRET: ${{ secrets.ONRAMPER_SIGNING_SECRET }}

jobs:
  extract-version:
    runs-on: ubuntu-24.04
    outputs:
      new_version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: extract-version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.3.0

      - name: print-version
        run: echo ${{ steps.extract_version.outputs.version }}

  publish-chrome-extension:
    name: publish-chrome-extension
    runs-on: ubuntu-24.04
    environment: extension:production
    needs:
      - extract-version
    outputs:
      publish_status: ${{ steps.publish-chrome.outputs.publish_status }}
    env:
      TARGET_BROWSER: chromium
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: build-packages
        run: pnpm build:packages

      - name: build-project
        working-directory: apps/extension
        env:
          # We only add the sentry auth token for chrome, as we don't want to
          # create a duplicate release during the ff build
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: pnpm build

      - uses: actions/upload-artifact@v4
        name: Upload build artifact
        with:
          name: leather-chromium-v${{ needs.extract-version.outputs.new_version }}
          path: apps/extension/dist

      - name: build-extension
        working-directory: apps/extension
        run: sh build-ext.sh

      - name: sign-and-upload-production-chrome-extension
        continue-on-error: true
        working-directory: apps/extension
        id: publish-chrome
        run: |
          pnpm chrome-webstore-upload upload --auto-publish --source leather-chromium.zip
          echo "publish_status=${?}" >> "$GITHUB_OUTPUT"
        env:
          EXTENSION_ID: ${{ secrets.CHROME_APP_ID }}
          CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

  create-github-release:
    name: create-github-release
    runs-on: ubuntu-24.04
    needs:
      - extract-version
      - publish-chrome-extension
    steps:
      - name: download-extension-build
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: zip-chromium-build
        run: zip -r leather-chromium.v${{ needs.extract-version.outputs.new_version }}.zip leather-chromium-v${{ needs.extract-version.outputs.new_version }}

      - name: update-release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            leather-chromium.v${{ needs.extract-version.outputs.new_version }}.zip

  post-run:
    runs-on: ubuntu-24.04
    needs:
      - publish-chrome-extension
    steps:
      - name: publish-statuses
        run: |
          echo "::warning::Chrome Publish Status: $([[ "${{ needs.publish-chrome-extension.outputs.publish_status }}" = "0" ]] && echo 'SUCCESS' || echo 'FAILED')"
