name: extension:code-checks

on:
  merge_group:
  push:
    branches:
      - '**'
    paths:
      - 'apps/extension/**'
      - 'packages/**'
      - '!packages/ui/**/*.native.ts'
      - '!packages/ui/**/*.native.tsx'

permissions:
  contents: read

jobs:
  lint-unused-exports:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: lint-unused-typescript-exports
        working-directory: apps/extension
        run: pnpm lint:unused-exports

  lint-firefox-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - run: pnpm build:packages

      - run: pnpm build
        working-directory: apps/extension
        env:
          TARGET_BROWSER: firefox

      - name: lint-firefox-build
        run: pnpm web-ext lint
        working-directory: apps/extension

  test-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: build
        run: pnpm build:extension

      - name: package-extension
        run: sh build-ext.sh
        working-directory: apps/extension
        shell: bash
