name: Trigger mobile preview builds for iOS and Android
on:
  pull_request:
    types:
      - synchronize
      - labeled
permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-eas-ios:
    if: contains(github.event.pull_request.labels.*.name, 'build:mobile:simulator')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/eas-deploy-ios
        with:
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          ASC_APP_ID: ${{ secrets.ASC_APP_ID }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          LEATHER_BOT: ${{ secrets.LEATHER_BOT }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy-eas-android:
    if: contains(github.event.pull_request.labels.*.name, 'build:mobile:simulator')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/eas-deploy-android
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          LEATHER_BOT: ${{ secrets.LEATHER_BOT }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON_B64 }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
