name: Mobile Firebase beta deployments
on:
  push:
    tags:
      - 'mobile-v*.*.*-beta.*'
      - 'mobile-test-v*.*.*-beta.*'
permissions:
  contents: write
  pull-requests: write

jobs:
  ios-beta:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup for Fastlane
        uses: ./.github/actions/setup-fastlane

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Provision
        uses: ./.github/actions/provision

      - name: Build iOS app
        working-directory: ./apps/mobile
        run: |
          eas build --local \
          --platform ios \
          --profile production \
          --non-interactive \
          --no-wait \
          --output ${{ github.workspace }}/app-release.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.ipa
          path: ${{ github.workspace }}/app-release.ipa

  android-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup for Fastlane
        uses: ./.github/actions/setup-fastlane

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Provision
        uses: ./.github/actions/provision

      - name: Build Android app
        working-directory: ./apps/mobile
        run: |
          eas build --local \
          --platform android \
          --profile production \
          --non-interactive \
          --no-wait \
          --output ${{ github.workspace }}/app-release.aab

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: ${{ github.workspace }}/app-release.aab

  upload-builds-to-firebase:
    needs:
      - ios-beta
      - android-beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload AAB to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: leatherhood
          file: ${{ github.workspace }}/app-release.aab

      - name: Upload IPA to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: leatherhood
          file: ${{ github.workspace }}/app-release.ipa

  create-beta-release:
    needs:
      - android-beta
      - ios-beta
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release notes for ${{ github.ref }}
          draft: false
      - name: Upload AAB to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/app-release.aab
          asset_name: app-release-${{ github.ref }}.aab
          asset_content_type: application/vnd.android.package-archive

      - name: Upload IPA to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/app-release.ipa
          asset_name: app-release-${{ github.ref }}.ipa
          asset_content_type: application/octet-stream
