name: mobile:deploy-production

# GITHUB_TOKEN only needs to read the repository for checkout.
permissions:
  contents: read
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-submit-mobile:
    name: build-and-submit-mobile
    runs-on: ubuntu-latest
    environment: mobile:production
    outputs:
      build_output: ${{ steps.build_and_submit.outputs.build_output }}
      android_build_id: ${{ steps.build_and_submit.outputs.android_build_id }}
      ios_build_id: ${{ steps.build_and_submit.outputs.ios_build_id }}
      build_version: ${{ steps.build_and_submit.outputs.build_version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: provision-the-app
        uses: ./.github/actions/provision
        with:
          PROVISION_MOBILE: true

      - name: setup-expo-and-eas
        uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # 8.2.1
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: install-jq-tool
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: build-and-submit-mobile
        id: build_and_submit
        working-directory: ./apps/mobile
        run: |
          build_output=$(eas build --non-interactive --json --no-wait --auto-submit --platform=all --profile=production)
          {
            echo "build_output=$(echo "$build_output" | base64 -w 0)"
            echo "android_build_id=$(echo "$build_output" | jq -r '.[0].["id"]')"
            echo "ios_build_id=$(echo "$build_output" | jq -r '.[1].["id"]')"
            echo "build_version=$(eas config -e production -p android --json --non-interactive | jq -r '.appConfig.version')"
          } >> "$GITHUB_OUTPUT"
