name: Build mobile preview of PR

on:
  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  preview-pr-build:
    runs-on: ubuntu-latest
    # if: contains(github.event.pull_request.labels.*.name, 'build:mobile:simulator')
    concurrency: fingerprint-${{ github.run_id }}
    permissions:
      # REQUIRED: Allow comments of PRs
      pull-requests: write # Allow comments on PRs
      # REQUIRED: Allow updating fingerprint in acton caches
      actions: write
      # Following permissions are required for private repos
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Provision
        uses: ./.github/actions/provision

      - name: Set CI
        run: |
          echo "CI=1" >> $GITHUB_ENV

      - name: 🚀 Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --branch ${{ github.event.pull_request.head.ref }} --environment=preview --message "Build preview for PR https://github.com/$GITHUB_REPOSITORY/pull/${{ github.event.pull_request.number }}"
          working-directory: apps/mobile
