name: Mobile Preview Builds
on:
  pull_request:
    types:
      - synchronize
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  mobile-pr-build:
    if: contains(github.event.pull_request.labels.*.name, 'build:mobile:simulator')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Provision the app
        uses: ./.github/actions/provision
        with:
          PROVISION_MOBILE: true

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Build and submit mobile
        id: preview_build
        working-directory: ./apps/mobile
        run: |
          build_output=$(eas build --no-wait --non-interactive --json --platform=all --profile=preview)
          android_build_id=$(echo $build_output | jq -r '.[0].["id"]')
          ios_build_id=$(echo $build_output | jq -r '.[1].["id"]')
          echo "android_build_id=$android_build_id" >> $GITHUB_OUTPUT
          echo "ios_build_id=$ios_build_id" >> $GITHUB_OUTPUT

      - name: Publish simulator expo link in PR
        uses: actions/github-script@v7
        if: ${{ steps.preview_build.outcome == 'success' }}
        env:
          ANDROID_BUILD_ID: ${{ steps.preview_build.outputs.android_build_id }}
          IOS_BUILD_ID: ${{ steps.preview_build.outputs.ios_build_id }}
        with:
          github-token: ${{ secrets.LEATHER_BOT }}
          script: |
            const { ANDROID_BUILD_ID, IOS_BUILD_ID } = process.env;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `iOS Build: https://expo.dev/accounts/leather-wallet/projects/leather-wallet-mobile/builds/${IOS_BUILD_ID}\n\n Android Build: https://expo.dev/accounts/leather-wallet/projects/leather-wallet-mobile/builds/${ANDROID_BUILD_ID}`
            })
