name: Mobile beta deploy
on:
  push:
    tags:
      - 'mobile-v*.*.*-beta.*'
permissions:
  contents: write
  pull-requests: write

jobs:
  ios-beta:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build iOS app
        id: build-ios
        uses: ./.github/actions/build-ios
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          GOOGLE_SERVICES_INFO_PLIST_B64: ${{ secrets.GOOGLE_SERVICES_INFO_PLIST_B64 }}

  android-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Android app
        id: build-android
        uses: ./.github/actions/build-android
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          GOOGLE_SERVICES_JSON_B64: ${{ secrets.GOOGLE_SERVICES_JSON_B64 }}

  update-changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get previous tag
        id: previousTag
        run: |
          current_tag=${{ github.ref_name }}
          current_version=$(echo $current_tag | grep -o "mobile-v[0-9]*\.[0-9]*\.[0-9]*")
          previous_tag=$(git tag --sort=v:refname | grep -E "mobile(-test)?-v[0-9]*\.[0-9]*\.[0-9]*-beta" | grep -v "$current_version" | head -n 1)
          echo $previous_tag
          echo "tag=$previous_tag" >> "$GITHUB_OUTPUT"

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ steps.previousTag.outputs.tag }}
          writeToFile: false

  upload-to-firebase:
    needs:
      - update-changelog
      - android-beta
      - ios-beta
    # This workflow can only run on ubuntu because the firebase_upload step only supports ubuntu
    runs-on: ubuntu-latest
    outputs:
      firebase_console_uri_ios: ${{ steps.firebase_upload_ipa.outputs.FIREBASE_CONSOLE_URI }}
      firebase_console_uri_android: ${{ steps.firebase_upload_aab.outputs.FIREBASE_CONSOLE_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download AAB artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release.aab
          path: ${{ github.workspace }}

      - name: Download IPA artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release.ipa
          path: ${{ github.workspace }}

      - name: Upload IPA to Firebase App Distribution
        id: firebase_upload_ipa
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_IOS}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: leatherhood
          file: ${{ github.workspace }}/app-release.ipa
          releaseNotes: ${{ needs.update-changelog.outputs.changelog }}

      - name: Upload AAB to Firebase
        id: firebase_upload_aab
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: leatherhood
          file: ${{ github.workspace }}/app-release.aab
          releaseNotes: ${{ needs.update-changelog.outputs.changelog }}

  create-beta-release:
    needs:
      - upload-to-firebase
      - update-changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.LEATHER_BOT }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: '@leather/mobile: ${{ github.ref_name }}'
          body: |
            ## Version: ${{ github.ref_name }}
            [Android - Firebase Console Link](${{ needs.upload-to-firebase.outputs.firebase_console_uri_android }})
            [iOS - Firebase Console Link](${{ needs.upload-to-firebase.outputs.firebase_console_uri_ios }})

            ---

            ## What's Changed?
            ${{ needs.update-changelog.outputs.changelog }}
          draft: true

      - name: Download AAB artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release.aab
          path: ${{ github.workspace }}

      - name: Download IPA artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release.ipa
          path: ${{ github.workspace }}

      - name: Upload AAB to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.LEATHER_BOT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/app-release.aab
          asset_name: ${{ github.ref }}.aab
          asset_content_type: application/vnd.android.package-archive

      - name: Upload IPA to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.LEATHER_BOT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/app-release.ipa
          asset_name: ${{ github.ref }}.ipa
          asset_content_type: application/octet-stream
