name: Mobile Firebase beta deployments
on:
  push:
    tags:
      - 'mobile-v*.*.*-beta.*'
      - 'mobile-test-v*'
permissions:
  contents: write
  pull-requests: write

jobs:
  ios-beta:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup for Fastlane
        uses: ./.github/actions/setup-fastlane

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Provision
        uses: ./.github/actions/provision

      - name: Build iOS app
        working-directory: ./apps/mobile
        run: |
          eas build --local \
          --platform ios \
          --profile production \
          --non-interactive \
          --no-wait \
          --output ${{ github.workspace }}/app-release.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.ipa
          path: ${{ github.workspace }}/app-release.ipa

      - name: Upload IPA to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: leatherhood
          file: ${{ github.workspace }}/app-release.ipa

  android-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup for Fastlane
        uses: ./.github/actions/setup-fastlane

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Provision
        uses: ./.github/actions/provision

      - name: Build Android app
        working-directory: ./apps/mobile
        run: |
          eas build --local \
          --platform android \
          --profile production \
          --non-interactive \
          --no-wait \
          --output ${{ github.workspace }}/app-release.aab

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: ${{ github.workspace }}/app-release.aab

      - name: Upload AAB to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: leatherhood
          file: ${{ github.workspace }}/app-release.aab

  # distribute-ios-beta:
  #   if: contains(github.event.pull_request.labels.*.name, 'needs:demo-build')
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup for Fastlane
  #       uses: ./.github/actions/setup-fastlane

  #     - name: iOS Fastlane Beta Deployment
  #       run: bundle exec fastlane ios distribute_ios_beta
  #       working-directory: ./apps/mobile/fastlane
  #       env:
  #         APPLE_ID: ${{ secrets.APPLE_ID }}
  #         EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  #         APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}

  # distribute-android-beta:
  #   if: contains(github.event.pull_request.labels.*.name, 'needs:demo-build')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup for Fastlane
  #       uses: ./.github/actions/setup-fastlane

  #     - name: Set up JDK
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: 'temurin'
  #         java-version: '17'

  #     - name: Android Fastlane Beta Deployment
  #       working-directory: ./apps/mobile/fastlane
  #       run: bundle exec fastlane android distribute_android_beta
  #       env:
  #         LEATHER_BOT: ${{ secrets.LEATHER_BOT }}
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  #         GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON_B64 }}
  #         ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
