name: packages:sanity-studio

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  deployments: write

jobs:
  deploy-sanity-studio:
    runs-on: ubuntu-latest
    name: deploy-sanity-studio
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: build-cms-app-deps
        run: pnpm turbo run build --filter="@leather.io/cms"

      - name: build-sanity-studio
        working-directory: packages/cms
        run: pnpm run sanity:build

      - name: deploy-cms-app
        working-directory: packages/cms
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: pnpm run sanity:deploy
