on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

name: Release packages

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      changelog: ${{ steps.release.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.LEATHER_BOT }}

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          # this assumes that you have created a personal access token (PAT)
          token: ${{ secrets.LEATHER_BOT }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          default-branch: dev
          release-type: 'minor'
          signoff: 'leather-bot <leather-bot@leather.io>'

    # The logic below handles the npm publication:
  deploy:
    needs: release-please
    runs-on: ubuntu-latest
    # Ensure we only publish if a new release was created
    if: needs.release-please.outputs.releases_created
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: Build packages
        run: pnpm build

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: pnpm --filter="./packages/*" publish --no-git-checks
