on:
  push:
    branches:
      - release-please/bootstrap/default

permissions:
  contents: write
  pull-requests: write

name: Release packages

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release-created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          # this assumes that you have created a personal access token (PAT)
          token: ${{ secrets.LEATHER_BOT }}
          # optional. customize path to release-please-config.json
          config-file: ../../release-please-config.json
          # optional. customize path to .release-please-manifest.json
          manifest-file: ../../.release-please-manifest.json

          # TESTING
          target-branch: release-please/bootstrap/default

  # The logic below handles the npm publication:
  deploy:
    needs: release-please
    runs-on: ubuntu-latest
    # these if statements ensure that a publication only occurs when
    # a new release is created:
    if: needs.release-please.outputs.release-created
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '^8.15'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
