on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

name: Release packages

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{ secrets.LEATHER_BOT }}
          default-branch: dev

    # TODO(leather-wallet/mono#133): get this back when release-please-action@4 gets an update for pnpm node workspaces.
    # steps:
    #   - uses: google-github-actions/release-please-action@v4
    #     id: release
    #     with:
    #       # this assumes that you have created a personal access token (PAT)
    #       token: ${{ secrets.LEATHER_BOT }}
    #       # optional. customize path to release-please-config.json
    #       config-file: release-please-config.json
    #       # optional. customize path to .release-please-manifest.json
    #       manifest-file: .release-please-manifest.json
    #       # Our target branch should be `dev`
    #       target-branch: dev

  # The logic below handles the npm publication:
  deploy:
    needs: release-please
    runs-on: ubuntu-latest
    # Ensure we only publish if a new release was created
    if: needs.release-please.outputs.releases_created
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - run: pnpm build

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: pnpm -r publish --no-git-checks
