name: repo:all-checks-pass
on:
  merge_group:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read

    steps:
      - name: check-if-is-merge-queue
        run: |
          if [[ "${{ github.ref }}" == refs/heads/gh-readonly-queue* ]]; then
            echo "IS_MERGE_QUEUE=true" >> $GITHUB_ENV
          else
            echo "IS_MERGE_QUEUE=false" >> $GITHUB_ENV
          fi

      - uses: wechuli/allcheckspassed@v1
        if: env.IS_MERGE_QUEUE != 'true'
        with:
          checks_exclude: 'Mobile Preview Builds'
