name: repo:code-checks

on:
  merge_group:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  lint-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision
      - name: lint-prettier
        run: pnpm format:check

  lint-syncpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision
      - name: lint-packages-with-syncpack
        run: pnpm syncpack:lint

  lint-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision
      - name: lint-eslint
        run: pnpm build && pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision
      - name: run-typecheck-recursively-in-each-package
        run: pnpm build && pnpm typecheck

  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: lint-commit-message
        uses: wagoid/commitlint-github-action@v6

  lint-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: lint-dependency-rules
        run: pnpm build && pnpm lint:deps

  lint-filenames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: lint-dependency-rules
        run: pnpm lint:filenames

  knip:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - run: pnpm build

      - name: knip
        run: pnpm knip

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - run: pnpm build

      - name: run-unit-tests-with-code-coverage
        run: pnpm test:unit

  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/provision

      - run: pnpm build

      - name: run-unit-tests-with-code-coverage
        run: pnpm test:coverage

      - name: upload-results-to-codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./app/mobile/coverage/.tmp/coverage-0.json

  audit-dependencies:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: audit
        run: pnpm dlx pnpm@11.0.0-rc.1 audit --prod --audit-level high --config.manage-package-manager-versions=false
