name: repo:workflow-checks

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  validate-workflow-names:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: validate-workflow-naming-convention
        run: bash .github/scripts/validate-workflow-names.sh

  validate-job-names:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: validate-job-naming-convention
        run: bash .github/scripts/validate-job-names.sh

  validate-step-names:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: validate-step-naming-convention
        run: bash .github/scripts/validate-step-names.sh

  validate-filenames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: validate-filename-matches-workflow-name
        run: bash .github/scripts/validate-filename-conventions.sh

  lint-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install-actionlint
        id: get_actionlint
        run: bash .github/scripts/install-action-lint.sh

      - name: lint-github-workflows
        run: ${{ steps.get_actionlint.outputs.executable }} -color
