name: Sign Release Commit

on:
  pull_request:
    branches:
      - release-please*
    types:
      - synchronize
  push:
    branches:
      - release-please*

permissions:
  contents: write

jobs:
  sign-release-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.LEATHER_BOT }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set leather-bot user
        run: |
          git config user.name "leather-bot"
          git config user.email "leather-bot@leather.io"

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.LEATHER_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.LEATHER_BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Rebase and sign commit
        run: |
          git fetch origin
          git rebase --exec 'git commit -S --amend --no-edit -n' @{upstream}
          git push --force-with-lease
