name: Test E2E

on:
  push:
    branches:
      - dev

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare the app
        uses: ./.github/actions/provision

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: deploy E2E build on EAS
        working-directory: ./apps/mobile
        run: |
          eas build --profile build-and-maestro-test --platform ios --non-interactive
