name: Update Mobile Versions
on:
  push:
    branches:
      - release/mobile/v*.*.*
    # tags were useful for testing, and keeping them here for now in case I want to
    # use them again for this process. But I need to merge and test the branch workflow
    # first.
    # tags:
    #   - 'mobile-v*.*.*(-beta.?|-alpha.?|-rc.?)?*'
    #   - 'mobile-v*.*.*'

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch for ref
        id: ref_branch
        run: |
          raw_branch=$(git branch -r --contains ${{ github.ref }})
          branch=${raw_branch##*origin/}
          echo "branch=$branch" >> $GITHUB_OUTPUT
          if [ -z "$branch" ]; then
            echo "No branch found for tag ${{ github.ref }}"
            exit 1
          fi
          echo "Branch is $branch."

      - name: Get current version
        uses: ./.github/actions/previous-mobile-tag
        id: previous-tag

      - name: Extract version from tag without v prefix
        run: |
          raw_version=${{steps.previous-tag.outputs.current_version}}
          echo "VERSION=${raw_version#v}" >> $GITHUB_ENV

      - name: Update gradle version for Android
        uses: damienaicheh/update-android-version-gradle-action@v1.0.0
        with:
          build-gradle-path: './apps/mobile/android/app/build.gradle'
          version-code: 1 # No need to set this, eas handles bumping the version code
          version-name: ${{env.VERSION}}
          print-file: true
        env:
          VERSION: ${{env.VERSION}}

      - name: Update Info.plist
        uses: damienaicheh/update-ios-version-info-plist-action@v1.2.0
        with:
          info-plist-path: './apps/mobile/ios/leatherwalletmobile/Info.plist'
          bundle-short-version-string: ${{env.VERSION}}
          bundle-version: 1
          print-file: true
        env:
          VERSION: ${{env.VERSION}}

      - name: Update version in app.config.js
        working-directory: ./apps/mobile
        # Note if you want to debug this on macos you'll need to use sed -i '' <rest of command>
        run: |
          sed -i "s/version: '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*'/version: '$VERSION'/g" app.config.js

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.LEATHER_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.LEATHER_BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit version bump to release branch
        run: |
          git config --global user.name "leather-bot <leather-bot@users.noreply.github.com>"
          git config --global user.email "leather-bot <leather-bot@users.noreply.github.com>"
          git fetch
          git checkout ${{ steps.ref_branch.outputs.branch }}
          git add .
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "chore: bump mobile iOS / Android versions to ${{ env.VERSION }}"
          git push origin ${{ steps.ref_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.LEATHER_BOT }}
          VERSION: ${{ env.VERSION }}

      - name: Get commit hash of version bump
        if: success()
        run: echo "VERSION_BUMP_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create version bump branch off dev
        if: success()
        run: |
          if [ -z "$VERSION_BUMP_COMMIT" ]; then
            echo "No version bump commit found, skipping PR creation"
            exit 0
          fi
          git fetch
          git checkout dev
          git cherry-pick --no-commit ${{ env.VERSION_BUMP_COMMIT }}
        env:
          GITHUB_TOKEN: ${{ secrets.LEATHER_BOT }}
          VERSION: ${{ env.VERSION }}
          VERSION_BUMP_COMMIT: ${{ env.VERSION_BUMP_COMMIT }}

      - name: Open PR to merge version bump into dev
        uses: peter-evans/create-pull-request@v6
        if: success()
        with:
          base: dev
          branch: version-bump/${{ env.VERSION }}
          title: 'chore: bump mobile iOS / Android versions to ${{ env.VERSION }}'
          commit-message: 'chore: bump mobile iOS / Android versions to ${{ env.VERSION }}'
          body: 'This PR updates app.config.js, build.grade and Info.plist to reflect the latest published release.'
          committer: 'leather-bot <leather-bot@users.noreply.github.com>'
          author: 'leather-bot <leather-bot@users.noreply.github.com>'
          token: ${{ secrets.LEATHER_BOT }}
        env:
          VERSION: ${{ env.VERSION }}
