name: web:integration-tests
on:
  pull_request:
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - '!packages/ui/**/*.native.ts'
      - '!packages/ui/**/*.native.tsx'

env:
  LEATHER_LAUNCH_DARKLY_KEY: ${{ secrets.WEB_LAUNCH_DARKLY_KEY }}

jobs:
  test:
    name: shard-${{ matrix.shardIndex }}-of-${{ matrix.shardTotal }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
    defaults:
      run:
        working-directory: apps/web

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: get-installed-playwright-version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'])")" >> "$GITHUB_ENV"

      - name: cache-playwright-binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-cache-${{ env.PLAYWRIGHT_VERSION }}

      - name: install-playwright-browsers
        run: pnpm exec playwright install chrome chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: install-playwright-deps
        run: pnpm exec playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: prepare-script
        run: pnpm --filter=@leather.io/web run prepare:build

      - name: build-packages
        working-directory: ./
        run: pnpm turbo run build --filter="@leather.io/web"

      - name: run-playwright-tests
        run: pnpm exec playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: upload-blob-report-to-github-actions-artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: apps/web/blob-report
          retention-days: 1
          if-no-files-found: error

  merge-reports:
    name: merge-reports
    if: always()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: download-blob-reports-from-github-actions-artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: merge-into-html-report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: extract-branch-name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_OUTPUT"
        id: extract_branch

      - uses: Wandalen/wretry.action@master
        if: github.event_name == 'pull_request'
        with:
          action: peaceiris/actions-gh-pages@v4
          with: |
            personal_token: ${{ secrets.LEATHER_BOT }}
            external_repository: leather-io/playwright-reports
            publish_branch: main
            publish_dir: ./playwright-report
            destination_dir: web/${{ steps.extract_branch.outputs.branch }}
