name: web:integration-tests
on:
  pull_request:
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - '!packages/ui/**/*.native.ts'
      - '!packages/ui/**/*.native.tsx'

env:
  LEATHER_LAUNCH_DARKLY_KEY: ${{ secrets.WEB_LAUNCH_DARKLY_KEY }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      LEATHER_MOCK_MODE: true

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: get-installed-playwright-version
        id: playwright-version
        working-directory: apps/web
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'])")" >> "$GITHUB_ENV"

      - name: cache-playwright-binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-cache-${{ env.PLAYWRIGHT_VERSION }}

      - name: install-playwright-browsers
        working-directory: apps/web
        run: pnpm exec playwright install chrome chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: install-playwright-deps
        working-directory: apps/web
        run: pnpm exec playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: prepare-script
        working-directory: apps/web
        run: pnpm prepare

      - name: build-packages
        run: pnpm turbo run build --filter="@leather.io/web"

      - name: run-playwright-tests
        working-directory: apps/web
        run: pnpm exec playwright test

      - name: upload-report-to-github-actions-artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: apps/web/test-results
          retention-days: 1
          if-no-files-found: error
