name: web:preview-build

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - 'apps/web/**'
      - 'packages/**'

env:
  DO_NOT_TRACK: 1

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: web-preview-build
          GITHUB_TOKEN: ${{ secrets.LEATHER_BOT }}
          message: |
            _Building web app preview at ${{ github.event.pull_request.head.sha }}_

      - uses: actions/checkout@v4
      - uses: ./.github/actions/provision

      - name: build-web-app-dependencies
        run: pnpm turbo run build --filter=@leather.io/web^...

      - name: build-web-app
        working-directory: apps/web
        env:
          LEATHER_FRONT_WEB_APP_API_TOKEN: ${{ secrets.FRONT_WEB_APP_API_TOKEN }}
        run: pnpm run build

      - name: upload-preview-version
        working-directory: apps/web
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_LEATHER_ACCOUNT_ID }}
        id: wrangler-upload
        run: pnpm wrangler versions upload --preview-alias pr-${{ github.event.pull_request.number }} > wrangler-preview.txt

      - name: output-wrangler-preview-file
        working-directory: apps/web
        run: cat wrangler-preview.txt

      - name: set-preview-url-environment-variable
        working-directory: apps/web
        run: echo "PREVIEW_URL=$(grep -o 'https://pr-${{ github.event.pull_request.number }}[^ ]*' wrangler-preview.txt | head -1)" >> "$GITHUB_ENV"

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: web-preview-build
          GITHUB_TOKEN: ${{ secrets.LEATHER_BOT }}
          message: |
            Leather Web Build ${{ github.event.pull_request.head.sha }} → ${{ env.PREVIEW_URL }}
